// packages/web/src/app/pages/playlists/playlists.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { ApiService, type Playlist, type PlaylistDetail } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { PlayerService, type Track } from '../../services/player.service';
import { ListControlsService, type SortOption } from '../../services/list-controls.service';
import { ListToolbarComponent } from '../../components/list-toolbar/list-toolbar.component';
import { TrackRowComponent } from '../../components/track-row/track-row.component';
import { toTrack } from '../../lib/track-utils';

// Deterministic gradient from playlist name
const GRADIENTS = [
  'from-indigo-500 to-purple-600',
  'from-pink-500 to-rose-600',
  'from-teal-500 to-cyan-600',
  'from-amber-500 to-red-600',
  'from-emerald-500 to-teal-600',
  'from-blue-500 to-indigo-600',
  'from-violet-500 to-fuchsia-600',
  'from-orange-500 to-amber-600',
];

function gradientFor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = ((hash << 5) - hash + name.charCodeAt(i)) | 0;
  return GRADIENTS[Math.abs(hash) % GRADIENTS.length];
}

function formatTotalDuration(seconds: number) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

function timeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const days = Math.floor(diff / 86_400_000);
  if (days === 0) return 'Added today';
  if (days === 1) return 'Added yesterday';
  if (days < 30) return `Added ${days} days ago`;
  return `Added ${new Date(dateStr).toLocaleDateString()}`;
}

interface DetailItem {
  id: string;
  title: string;
  artist: string;
  album: string;
  duration?: number;
  track?: number;
  coverArt?: string;
  _originalIndex: number;
}

@Component({
  selector: 'app-playlists',
  imports: [FormsModule, ListToolbarComponent, TrackRowComponent],
  template: `
    <!-- Detail view -->
    @if (selected()) {
      <div class="max-w-6xl mx-auto px-3 py-4 md:px-6 md:py-8">
        <button (click)="selected.set(null)"
          class="text-sm text-zinc-500 hover:text-zinc-300 transition mb-6">
          &larr; Back to playlists
        </button>

        <div class="flex flex-col sm:flex-row items-center sm:items-end gap-6 mb-8 text-center sm:text-left">
          @if (selected()!.coverArt) {
            <img [src]="'/api/cover/' + selected()!.coverArt + '?size=300&token=' + auth.token()"
              alt="" class="w-48 h-48 rounded-lg object-cover flex-shrink-0" />
          } @else {
            <div [class]="'w-48 h-48 rounded-lg bg-gradient-to-br ' + gradientFor(selected()!.name) + ' flex items-center justify-center flex-shrink-0'">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="opacity-40">
                <path d="M9 18V5l12-2v13" /><circle cx="6" cy="18" r="3" /><circle cx="18" cy="16" r="3" />
              </svg>
            </div>
          }
          <div class="flex flex-col justify-end">
            @if (editingName()) {
              <input autofocus
                [ngModel]="nameDraft()"
                (ngModelChange)="nameDraft.set($event)"
                (blur)="saveRename()"
                (keydown.enter)="saveRename()"
                (keydown.escape)="editingName.set(false)"
                class="text-2xl font-bold text-zinc-100 bg-transparent border-b border-zinc-600 focus:border-zinc-400 outline-none pb-0.5" />
            } @else {
              <h1 class="text-2xl font-bold text-zinc-100 cursor-pointer hover:text-zinc-300 transition"
                (click)="startRename()" title="Click to rename">
                {{ selected()!.name }}
              </h1>
            }
            <p class="text-zinc-400 mt-1">
              {{ selected()!.entry?.length ?? selected()!.songCount }} tracks · {{ formatTotalDuration(selected()!.duration) }}
            </p>
            <div class="flex justify-center sm:justify-start gap-3 mt-4">
              <button (click)="playAll()"
                class="px-5 py-2 rounded-lg bg-zinc-100 text-zinc-900 text-sm font-semibold hover:bg-zinc-200 transition">
                Play All
              </button>
              <!-- TODO: Preserve All (Phase 5) -->
              <button (click)="handleDelete()" [disabled]="deleting()"
                class="px-4 py-2 rounded-lg bg-zinc-800 text-zinc-400 text-sm font-medium hover:bg-zinc-700 hover:text-red-400 transition disabled:opacity-50">
                {{ deleting() ? 'Deleting...' : 'Delete' }}
              </button>
            </div>
          </div>
        </div>

        @if (detailControls.isToolbarVisible()) {
          <app-list-toolbar
            [searchText]="detailControls.searchText()"
            [sortField]="detailControls.sortField()"
            [sortDirection]="detailControls.sortDirection()"
            [sortOptions]="detailSortOptions"
            [resultCount]="detailControls.filtered().length"
            (searchChange)="detailControls.setSearchText($event)"
            (sortFieldChange)="detailControls.setSortField($event)"
            (toggleDirection)="detailControls.toggleSortDirection()"
            (dismiss)="detailControls.hideToolbar()"
          />
        }

        <div>
          @for (song of detailControls.filtered(); track song.id + '-' + song._originalIndex) {
            <app-track-row
              [track]="toTrackFromSong(song)"
              [indexLabel]="song.track ?? song._originalIndex + 1"
              [subtitle]="song.artist"
              [duration]="song.duration"
              [disabled]="removing().has(song._originalIndex)"
              [showRemove]="true"
              (play)="playSong(song)"
              (remove)="removeSong(song._originalIndex)"
            />
          }
        </div>
      </div>
    } @else {
      <!-- Grid view -->
      <div class="max-w-6xl mx-auto px-3 py-4 md:px-6 md:py-8">
        <div class="flex items-center gap-3 mb-6">
          <h1 class="text-lg font-semibold text-zinc-100">Playlists</h1>
          <button (click)="gridControls.showToolbar()" class="p-1 text-zinc-600 hover:text-zinc-300 transition" title="Search (Ctrl+F)">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" /></svg>
          </button>
        </div>

        @if (gridControls.isToolbarVisible()) {
          <app-list-toolbar
            [searchText]="gridControls.searchText()"
            [sortField]="gridControls.sortField()"
            [sortDirection]="gridControls.sortDirection()"
            [sortOptions]="gridSortOptions"
            [resultCount]="gridControls.filtered().length"
            (searchChange)="gridControls.setSearchText($event)"
            (sortFieldChange)="gridControls.setSortField($event)"
            (toggleDirection)="gridControls.toggleSortDirection()"
            (dismiss)="gridControls.hideToolbar()"
          />
        }

        @if (loading()) {
          <div class="text-center py-20">
            <span class="inline-block w-5 h-5 border-2 border-zinc-600 border-t-zinc-300 rounded-full animate-spin"></span>
          </div>
        }

        @if (!loading() && playlists().length === 0) {
          <p class="text-center text-zinc-600 py-20">
            No playlists yet. Download an album and one will be created automatically!
          </p>
        }

        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          @for (pl of gridControls.filtered(); track pl.id) {
            <button (click)="openPlaylist(pl)" [disabled]="loadingDetail()"
              class="p-3 rounded-lg bg-zinc-900/30 hover:bg-zinc-800/50 transition text-left">
              @if (pl.coverArt) {
                <img [src]="'/api/cover/' + pl.coverArt + '?size=300&token=' + auth.token()"
                  alt="" class="w-full aspect-square rounded object-cover mb-2" />
              } @else {
                <div [class]="'w-full aspect-square rounded bg-gradient-to-br ' + gradientFor(pl.name) + ' flex items-center justify-center mb-2'">
                  <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="opacity-40">
                    <path d="M9 18V5l12-2v13" /><circle cx="6" cy="18" r="3" /><circle cx="18" cy="16" r="3" />
                  </svg>
                </div>
              }
              <p class="text-sm text-zinc-200 truncate">{{ pl.name }}</p>
              <p class="text-xs text-zinc-500 truncate">
                {{ pl.songCount }} tracks · {{ timeAgo(pl.created) }}
              </p>
            </button>
          }
        </div>
      </div>
    }
  `,
})
export class PlaylistsComponent implements OnInit {
  private api = inject(ApiService);
  readonly auth = inject(AuthService);
  private player = inject(PlayerService);
  private listControls = inject(ListControlsService);

  readonly gradientFor = gradientFor;
  readonly formatTotalDuration = formatTotalDuration;
  readonly timeAgo = timeAgo;

  readonly playlists = signal<Playlist[]>([]);
  readonly loading = signal(true);
  readonly selected = signal<PlaylistDetail | null>(null);
  readonly loadingDetail = signal(false);
  readonly deleting = signal(false);
  readonly editingName = signal(false);
  readonly nameDraft = signal('');
  readonly removing = signal(new Set<number>());

  readonly detailItems = computed<DetailItem[]>(() => {
    const sel = this.selected();
    return (sel?.entry ?? []).map((song, idx) => ({ ...song, _originalIndex: idx }));
  });

  readonly gridSortOptions: SortOption[] = [
    { field: 'name', label: 'Name' },
    { field: 'created', label: 'Date created' },
    { field: 'songCount', label: 'Track count' },
  ];

  readonly detailSortOptions: SortOption[] = [
    { field: 'title', label: 'Title' },
    { field: 'artist', label: 'Artist' },
    { field: 'duration', label: 'Duration' },
  ];

  readonly gridControls = this.listControls.connect({
    pageKey: 'playlists',
    items: this.playlists,
    searchFields: ['name'] as const,
    sortOptions: this.gridSortOptions,
  });

  readonly detailControls = this.listControls.connect({
    pageKey: 'playlist-detail',
    items: this.detailItems,
    searchFields: ['title', 'artist', 'album'] as const,
    sortOptions: this.detailSortOptions,
  });

  ngOnInit(): void {
    this.fetchPlaylists();
  }

  async openPlaylist(pl: Playlist): Promise<void> {
    this.loadingDetail.set(true);
    try {
      const detail = await firstValueFrom(this.api.getPlaylist(pl.id));
      this.selected.set(detail);
    } catch { /* ignore */ }
    finally { this.loadingDetail.set(false); }
  }

  playSong(song: DetailItem): void {
    this.player.play(toTrack(song));
  }

  playAll(): void {
    const pl = this.selected();
    if (!pl?.entry?.length) return;
    const tracks = pl.entry.map((s): Track => ({
      id: s.id,
      title: s.title,
      artist: s.artist,
      album: s.album,
      coverArt: s.coverArt,
      duration: s.duration,
    }));
    this.player.playWithContext(tracks, 0, { type: 'playlist', id: pl.id, name: pl.name });
  }

  async handleDelete(): Promise<void> {
    const pl = this.selected();
    if (!pl) return;
    this.deleting.set(true);
    try {
      await firstValueFrom(this.api.deletePlaylist(pl.id));
      this.playlists.update(prev => prev.filter(p => p.id !== pl.id));
      this.selected.set(null);
    } catch { /* ignore */ }
    finally { this.deleting.set(false); }
  }

  startRename(): void {
    const pl = this.selected();
    if (!pl) return;
    this.nameDraft.set(pl.name);
    this.editingName.set(true);
  }

  async saveRename(): Promise<void> {
    const pl = this.selected();
    if (!pl) return;
    const trimmed = this.nameDraft().trim();
    if (!trimmed || trimmed === pl.name) {
      this.editingName.set(false);
      return;
    }
    try {
      await firstValueFrom(this.api.updatePlaylist(pl.id, { name: trimmed }));
      this.selected.set({ ...pl, name: trimmed });
      this.playlists.update(prev => prev.map(p => p.id === pl.id ? { ...p, name: trimmed } : p));
    } catch { /* ignore */ }
    this.editingName.set(false);
  }

  async removeSong(songIndex: number): Promise<void> {
    const pl = this.selected();
    if (!pl) return;
    this.removing.update(prev => new Set(prev).add(songIndex));
    try {
      await firstValueFrom(this.api.updatePlaylist(pl.id, { songIndexesToRemove: [songIndex] }));
      const updatedEntry = pl.entry?.filter((_, i) => i !== songIndex) ?? [];
      this.selected.set({ ...pl, entry: updatedEntry, songCount: updatedEntry.length });
      this.playlists.update(prev => prev.map(p => p.id === pl.id ? { ...p, songCount: updatedEntry.length } : p));
    } catch { /* ignore */ }
    this.removing.update(prev => { const n = new Set(prev); n.delete(songIndex); return n; });
  }

  toTrackFromSong(song: DetailItem): Track {
    return toTrack(song);
  }

  private async fetchPlaylists(): Promise<void> {
    try {
      const data = await firstValueFrom(this.api.getPlaylists());
      this.playlists.set(data);
    } catch { /* ignore */ }
    finally { this.loading.set(false); }
  }
}


    <!-- Detail view -->
    @if (selected()) {
      <div class="max-w-6xl mx-auto px-3 py-4 md:px-6 md:py-8">
        <button (click)="selected.set(null)"
          class="text-sm text-theme-muted hover:text-theme-primary transition mb-6">
          &larr; Back to playlists
        </button>

        <div class="flex flex-col sm:flex-row items-center sm:items-end gap-6 mb-8 text-center sm:text-left">
          @if (selected()!.coverArt) {
            <img [src]="'/api/cover/' + selected()!.coverArt + '?size=300&token=' + auth.token()"
              alt="" class="w-48 h-48 rounded-lg object-cover flex-shrink-0" />
          } @else {
            <div [class]="'w-48 h-48 rounded-lg bg-gradient-to-br ' + gradientFor(selected()!.name) + ' flex items-center justify-center flex-shrink-0'">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="opacity-40">
                <path d="M9 18V5l12-2v13" /><circle cx="6" cy="18" r="3" /><circle cx="18" cy="16" r="3" />
              </svg>
            </div>
          }
          <div class="flex flex-col justify-end">
            <div class="flex items-center gap-2 flex-wrap">
              <h1 class="text-2xl font-bold text-theme-primary">{{ selected()!.name }}</h1>
              <button (click)="openRenameModal()"
                class="p-1 text-theme-muted hover:text-theme-primary transition" title="Rename">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/>
                </svg>
              </button>
            </div>
            <p class="text-theme-muted mt-1">
              {{ selected()!.entry?.length ?? selected()!.songCount }} tracks · {{ formatTotalDuration(selected()!.duration) }}
            </p>
            <div class="flex justify-center sm:justify-start gap-3 mt-4">
              <button (click)="playAll()"
                class="px-5 py-2 rounded-lg bg-theme-surface-2 text-theme-primary text-sm font-semibold hover:bg-theme-hover transition">
                Play All
              </button>
              <button (click)="sharePlaylist()"
                class="px-4 py-2 rounded-lg text-sm transition"
                [class]="shareCopied()
                  ? 'bg-emerald-500/20 text-emerald-400'
                  : 'bg-theme-surface-2 text-theme-muted hover:bg-theme-hover'">
                @if (shareCopied()) { Link copied! } @else { Share }
              </button>
              <!-- Offline download toggle -->
              <button (click)="togglePlaylistOffline()"
                [disabled]="playlistOfflineState() === 'downloading'"
                [title]="playlistOfflineState() === 'done' ? 'Remove offline copy' : 'Download for offline'"
                [class]="'px-4 py-2 rounded-lg text-sm font-medium transition disabled:opacity-50 '
                  + (playlistOfflineState() === 'done'
                    ? 'bg-emerald-500/20 text-emerald-400 hover:bg-emerald-500/30'
                    : 'bg-theme-surface-2 text-theme-muted hover:bg-theme-hover')">
                @switch (playlistOfflineState()) {
                  @case ('downloading') {
                    <span class="flex items-center gap-2">
                      <svg class="animate-spin" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M21 12a9 9 0 1 1-3-6.7" /><polyline points="21 3 21 9 15 9" />
                      </svg>
                      {{ playlistPreserveProgress().done }} / {{ playlistPreserveProgress().total }}
                    </span>
                  }
                  @case ('done') {
                    <span class="flex items-center gap-2">
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="20 6 9 17 4 12" />
                      </svg>
                      Downloaded
                    </span>
                  }
                  @default {
                    <span class="flex items-center gap-2">
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
                      </svg>
                      Download
                    </span>
                  }
                }
              </button>
              <button (click)="confirmDelete()" [disabled]="deleting()"
                class="px-4 py-2 rounded-lg bg-theme-surface-2 text-theme-muted text-sm font-medium hover:bg-theme-hover hover:text-red-400 transition disabled:opacity-50">
                {{ deleting() ? 'Deleting...' : 'Delete' }}
              </button>
            </div>
          </div>
        </div>

        <app-list-toolbar
          [searchText]="detailControls.searchText()"
          [sortField]="detailControls.sortField()"
          [sortDirection]="detailControls.sortDirection()"
          [sortOptions]="detailSortOptions"
          [resultCount]="detailControls.filtered().length"
          (searchChange)="detailControls.setSearchText($event)"
          (sortFieldChange)="detailControls.setSortField($event)"
          (toggleDirection)="detailControls.toggleSortDirection()"
        />

        <div>
          @for (song of detailControls.filtered(); track song.id + '-' + song._originalIndex) {
            <app-track-row
              [track]="toTrackFromSong(song)"
              [indexLabel]="song.track ?? song._originalIndex + 1"
              [subtitle]="song.artist"
              [duration]="song.duration"
              [disabled]="removing().has(song._originalIndex)"
              [showRemove]="false"
              [offline]="preserve.isPreserved(song.id)"
              [actions]="playlistTrackActions(song)"
              (play)="playSong(song)"
              (remove)="confirmRemoveSong(song._originalIndex, song.title)"
            />
          }
        </div>

        @if (showConfirm()) {
          <app-confirm-dialog
            [message]="confirmMessage()"
            [confirmLabel]="confirmLabel()"
            (confirm)="onConfirm()"
            (cancel)="onCancelConfirm()"
          />
        }
      </div>

      @if (showRenameModal()) {
        <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
             (click)="showRenameModal.set(false)">
          <div class="bg-theme-surface border border-theme rounded-xl p-6 max-w-sm w-full mx-4 shadow-2xl"
               (click)="$event.stopPropagation()">
            <h3 class="text-theme-primary font-medium mb-4">Rename playlist</h3>
            <input
              class="w-full bg-theme-surface-2 text-theme-primary text-sm px-3 py-2 rounded-lg outline-none border border-theme focus:border-blue-500/50 mb-4"
              [ngModel]="nameDraft()"
              (ngModelChange)="nameDraft.set($event)"
              (keydown.enter)="saveRename()"
              (keydown.escape)="showRenameModal.set(false)"
              autofocus
            />
            <div class="flex gap-3 justify-end">
              <button class="px-4 py-2 text-sm text-theme-secondary hover:text-theme-primary rounded-lg transition-colors"
                (click)="showRenameModal.set(false)">Cancel</button>
              <button class="px-4 py-2 text-sm bg-blue-500/20 text-blue-400 hover:bg-blue-500/30 rounded-lg transition-colors"
                (click)="saveRename()">Save</button>
            </div>
          </div>
        </div>
      }
    } @else {
      <!-- Grid view -->
      <div class="max-w-6xl mx-auto px-3 py-4 md:px-6 md:py-8">
        <div class="flex items-center gap-3 mb-6">
          <h1 class="text-lg font-semibold text-theme-primary">Playlists</h1>
        </div>

        <app-list-toolbar
          [searchText]="gridControls.searchText()"
          [sortField]="gridControls.sortField()"
          [sortDirection]="gridControls.sortDirection()"
          [sortOptions]="gridSortOptions"
          [resultCount]="gridControls.filtered().length"
          (searchChange)="gridControls.setSearchText($event)"
          (sortFieldChange)="gridControls.setSortField($event)"
          (toggleDirection)="gridControls.toggleSortDirection()"
        />

        @if (loading()) {
          <div class="text-center py-20">
            <span class="inline-block w-5 h-5 border-2 border-theme border-t-theme-secondary rounded-full animate-spin"></span>
          </div>
        }

        @if (!loading() && playlists().length === 0) {
          <p class="text-center text-theme-muted py-20">
            No playlists yet. Download an album and one will be created automatically!
          </p>
        }

        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          @for (pl of gridControls.filtered(); track pl.id) {
            <button (click)="openPlaylist(pl)" [disabled]="loadingDetail()"
              class="p-3 rounded-lg bg-theme-surface/30 hover:bg-theme-surface-2/50 transition text-left">
              @if (pl.coverArt) {
                <img [src]="'/api/cover/' + pl.coverArt + '?size=300&token=' + auth.token()"
                  alt="" class="w-full aspect-square rounded object-cover mb-2" />
              } @else {
                <div [class]="'w-full aspect-square rounded bg-gradient-to-br ' + gradientFor(pl.name) + ' flex items-center justify-center mb-2'">
                  <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="opacity-40">
                    <path d="M9 18V5l12-2v13" /><circle cx="6" cy="18" r="3" /><circle cx="18" cy="16" r="3" />
                  </svg>
                </div>
              }
              <p class="text-sm text-theme-primary truncate">{{ pl.name }}</p>
              <p class="text-xs text-theme-muted truncate">
                {{ pl.songCount }} tracks · {{ timeAgo(pl.created) }}
              </p>
            </button>
          }
        </div>
      </div>
    }

// packages/web/src/pages/Playlists.tsx
import { useState, useEffect, useMemo } from 'react';
import { api } from '@/lib/api';
import { useAuthStore } from '@/stores/auth';
import { usePlayerStore, type Track } from '@/stores/player';
import { usePreserveStore } from '@/stores/preserve';
import { toTrack } from '@/lib/trackUtils';
import { TrackRow } from '@/components/TrackRow';
import { useListControls } from '@/hooks/useListControls';
import { ListToolbar } from '@/components/ListToolbar';

interface Playlist {
  id: string;
  name: string;
  songCount: number;
  duration: number;
  owner: string;
  created: string;
  changed: string;
  coverArt?: string;
}

interface PlaylistSong {
  id: string;
  title: string;
  artist: string;
  album: string;
  duration?: number;
  track?: number;
  coverArt?: string;
}

interface PlaylistDetail extends Playlist {
  entry?: PlaylistSong[];
}

// Deterministic gradient from playlist name
const gradients = [
  'from-indigo-500 to-purple-600',
  'from-pink-500 to-rose-600',
  'from-teal-500 to-cyan-600',
  'from-amber-500 to-red-600',
  'from-emerald-500 to-teal-600',
  'from-blue-500 to-indigo-600',
  'from-violet-500 to-fuchsia-600',
  'from-orange-500 to-amber-600',
];

function gradientFor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = ((hash << 5) - hash + name.charCodeAt(i)) | 0;
  return gradients[Math.abs(hash) % gradients.length];
}

function formatTotalDuration(seconds: number) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

function timeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const days = Math.floor(diff / 86_400_000);
  if (days === 0) return 'Added today';
  if (days === 1) return 'Added yesterday';
  if (days < 30) return `Added ${days} days ago`;
  return `Added ${new Date(dateStr).toLocaleDateString()}`;
}

export function PlaylistsPage() {
  const [playlists, setPlaylists] = useState<Playlist[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<PlaylistDetail | null>(null);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [editingName, setEditingName] = useState(false);
  const [nameDraft, setNameDraft] = useState('');
  const [removing, setRemoving] = useState<Set<number>>(new Set());
  const token = useAuthStore((s) => s.token);
  const play = usePlayerStore((s) => s.play);
  const playWithContext = usePlayerStore((s) => s.playWithContext);
  const preserve = usePreserveStore((s) => s.preserve);

  // Detail items with original index preserved for removeSong
  const detailItems = useMemo(() =>
    (selected?.entry ?? []).map((song, idx) => ({ ...song, _originalIndex: idx })),
    [selected?.entry]
  );

  // Grid list controls
  const gridControls = useListControls({
    pageKey: 'playlists',
    items: playlists,
    searchFields: ['name'] as const,
    sortOptions: [
      { field: 'name', label: 'Name' },
      { field: 'created', label: 'Date created' },
      { field: 'songCount', label: 'Track count' },
    ],
  });

  // Detail list controls
  const detailControls = useListControls({
    pageKey: 'playlist-detail',
    items: detailItems,
    searchFields: ['title', 'artist', 'album'] as const,
    sortOptions: [
      { field: 'title', label: 'Title' },
      { field: 'artist', label: 'Artist' },
      { field: 'duration', label: 'Duration' },
    ],
  });

  useEffect(() => {
    api.getPlaylists()
      .then(setPlaylists)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  async function openPlaylist(pl: Playlist) {
    setLoadingDetail(true);
    try {
      const detail = await api.getPlaylist(pl.id);
      setSelected(detail);
    } catch {
      // ignore
    } finally {
      setLoadingDetail(false);
    }
  }

  function playSong(song: PlaylistSong) {
    play(toTrack(song));
  }

  function playAll(pl: PlaylistDetail) {
    if (!pl.entry?.length) return;
    const tracks = pl.entry.map((s): Track => ({
      id: s.id,
      title: s.title,
      artist: s.artist,
      album: s.album,
      coverArt: s.coverArt,
      duration: s.duration,
    }));
    playWithContext(tracks, 0, { type: 'playlist', id: pl.id, name: pl.name });
  }

  function preserveAll(pl: PlaylistDetail) {
    if (!pl.entry?.length) return;
    pl.entry.forEach((s) => preserve(toTrack(s), token));
  }

  async function handleDelete(pl: PlaylistDetail) {
    setDeleting(true);
    try {
      await api.deletePlaylist(pl.id);
      setPlaylists(prev => prev.filter(p => p.id !== pl.id));
      setSelected(null);
    } catch {
      // ignore
    } finally {
      setDeleting(false);
    }
  }

  function startRename(pl: PlaylistDetail) {
    setNameDraft(pl.name);
    setEditingName(true);
  }

  async function saveRename(pl: PlaylistDetail) {
    const trimmed = nameDraft.trim();
    if (!trimmed || trimmed === pl.name) {
      setEditingName(false);
      return;
    }
    try {
      await api.updatePlaylist(pl.id, { name: trimmed });
      setSelected({ ...pl, name: trimmed });
      setPlaylists(prev => prev.map(p => p.id === pl.id ? { ...p, name: trimmed } : p));
    } catch {
      // ignore
    }
    setEditingName(false);
  }

  async function removeSong(pl: PlaylistDetail, songIndex: number) {
    setRemoving(prev => new Set(prev).add(songIndex));
    try {
      await api.updatePlaylist(pl.id, { songIndexesToRemove: [songIndex] });
      const updatedEntry = pl.entry?.filter((_, i) => i !== songIndex) ?? [];
      const updated = { ...pl, entry: updatedEntry, songCount: updatedEntry.length };
      setSelected(updated);
      setPlaylists(prev => prev.map(p => p.id === pl.id ? { ...p, songCount: updatedEntry.length } : p));
    } catch {
      // ignore
    }
    setRemoving(prev => { const n = new Set(prev); n.delete(songIndex); return n; });
  }

  // Detail view
  if (selected) {
    return (
      <div className="max-w-6xl mx-auto px-3 py-4 md:px-6 md:py-8">
        <button
          onClick={() => setSelected(null)}
          className="text-sm text-zinc-500 hover:text-zinc-300 transition mb-6"
        >
          &larr; Back to playlists
        </button>

        <div className="flex flex-col sm:flex-row items-center sm:items-end gap-6 mb-8 text-center sm:text-left">
          {selected.coverArt ? (
            <img
              src={`/api/cover/${selected.coverArt}?size=300&token=${token}`}
              alt=""
              className="w-48 h-48 rounded-lg object-cover flex-shrink-0"
            />
          ) : (
            <div className={`w-48 h-48 rounded-lg bg-gradient-to-br ${gradientFor(selected.name)} flex items-center justify-center flex-shrink-0`}>
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="opacity-40">
                <path d="M9 18V5l12-2v13" />
                <circle cx="6" cy="18" r="3" />
                <circle cx="18" cy="16" r="3" />
              </svg>
            </div>
          )}
          <div className="flex flex-col justify-end">
            {editingName ? (
              <input
                autoFocus
                value={nameDraft}
                onChange={e => setNameDraft(e.target.value)}
                onBlur={() => saveRename(selected)}
                onKeyDown={e => { if (e.key === 'Enter') saveRename(selected); if (e.key === 'Escape') setEditingName(false); }}
                className="text-2xl font-bold text-zinc-100 bg-transparent border-b border-zinc-600 focus:border-zinc-400 outline-none pb-0.5"
              />
            ) : (
              <h1
                className="text-2xl font-bold text-zinc-100 cursor-pointer hover:text-zinc-300 transition"
                onClick={() => startRename(selected)}
                title="Click to rename"
              >
                {selected.name}
              </h1>
            )}
            <p className="text-zinc-400 mt-1">
              {selected.entry?.length ?? selected.songCount} tracks · {formatTotalDuration(selected.duration)}
            </p>
            <div className="flex justify-center sm:justify-start gap-3 mt-4">
              <button
                onClick={() => playAll(selected)}
                className="px-5 py-2 rounded-lg bg-zinc-100 text-zinc-900 text-sm font-semibold hover:bg-zinc-200 transition"
              >
                Play All
              </button>
              <button
                onClick={() => preserveAll(selected)}
                className="px-4 py-2 rounded-lg bg-zinc-800 text-zinc-300 text-sm font-medium hover:bg-zinc-700 transition"
                title="Save all tracks for offline"
              >
                Preserve All
              </button>
              <button
                onClick={() => handleDelete(selected)}
                disabled={deleting}
                className="px-4 py-2 rounded-lg bg-zinc-800 text-zinc-400 text-sm font-medium hover:bg-zinc-700 hover:text-red-400 transition disabled:opacity-50"
              >
                {deleting ? 'Deleting...' : 'Delete'}
              </button>
            </div>
          </div>
        </div>

        {detailControls.isToolbarVisible && (
          <ListToolbar
            searchText={detailControls.searchText}
            onSearchChange={detailControls.setSearchText}
            sortField={detailControls.sortField}
            onSortFieldChange={detailControls.setSortField}
            sortDirection={detailControls.sortDirection}
            onToggleSortDirection={detailControls.toggleSortDirection}
            sortOptions={detailControls.sortOptions}
            onDismiss={detailControls.hideToolbar}
            inputRef={detailControls.inputRef}
            resultCount={detailControls.filtered.length}
          />
        )}

        <div>
          {detailControls.filtered.map((song) => (
            <TrackRow
              key={`${song.id}-${song._originalIndex}`}
              track={toTrack(song)}
              indexLabel={song.track ?? song._originalIndex + 1}
              subtitle={song.artist}
              duration={song.duration}
              onPlay={() => playSong(song)}
              disabled={removing.has(song._originalIndex)}
              trailingAction={{
                title: 'Remove from playlist',
                onClick: () => removeSong(selected, song._originalIndex),
                icon: (
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                ),
              }}
            />
          ))}
        </div>
      </div>
    );
  }

  // Grid view
  return (
    <div className="max-w-6xl mx-auto px-3 py-4 md:px-6 md:py-8">
      <div className="flex items-center gap-3 mb-6">
        <h1 className="text-lg font-semibold text-zinc-100">Playlists</h1>
        <button onClick={gridControls.showToolbar} className="p-1 text-zinc-600 hover:text-zinc-300 transition" title="Search (Ctrl+F)">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" /></svg>
        </button>
      </div>

      {gridControls.isToolbarVisible && (
        <ListToolbar
          searchText={gridControls.searchText}
          onSearchChange={gridControls.setSearchText}
          sortField={gridControls.sortField}
          onSortFieldChange={gridControls.setSortField}
          sortDirection={gridControls.sortDirection}
          onToggleSortDirection={gridControls.toggleSortDirection}
          sortOptions={gridControls.sortOptions}
          onDismiss={gridControls.hideToolbar}
          inputRef={gridControls.inputRef}
          resultCount={gridControls.filtered.length}
        />
      )}

      {loading && (
        <div className="text-center py-20">
          <span className="inline-block w-5 h-5 border-2 border-zinc-600 border-t-zinc-300 rounded-full animate-spin" />
        </div>
      )}

      {!loading && playlists.length === 0 && (
        <p className="text-center text-zinc-600 py-20">
          No playlists yet. Download an album and one will be created automatically!
        </p>
      )}

      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
        {gridControls.filtered.map((pl) => (
          <button
            key={pl.id}
            onClick={() => openPlaylist(pl)}
            disabled={loadingDetail}
            className="p-3 rounded-lg bg-zinc-900/30 hover:bg-zinc-800/50 transition text-left"
          >
            {pl.coverArt ? (
              <img
                src={`/api/cover/${pl.coverArt}?size=300&token=${token}`}
                alt=""
                className="w-full aspect-square rounded object-cover mb-2"
              />
            ) : (
              <div className={`w-full aspect-square rounded bg-gradient-to-br ${gradientFor(pl.name)} flex items-center justify-center mb-2`}>
                <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="opacity-40">
                  <path d="M9 18V5l12-2v13" />
                  <circle cx="6" cy="18" r="3" />
                  <circle cx="18" cy="16" r="3" />
                </svg>
              </div>
            )}
            <p className="text-sm text-zinc-200 truncate">{pl.name}</p>
            <p className="text-xs text-zinc-500 truncate">
              {pl.songCount} tracks · {timeAgo(pl.created)}
            </p>
          </button>
        ))}
      </div>
    </div>
  );
}
