// packages/web/src/app/pages/setup/setup.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { ApiService, type SetupStatus } from '../../services/api.service';
import { SetupService } from '../../services/setup.service';
import { PasswordFieldComponent } from '../../components/password-field/password-field.component';

type Step = 'admin' | 'soulseek' | 'tailscale' | 'done';

@Component({
  selector: 'app-setup',
  imports: [FormsModule, PasswordFieldComponent],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-zinc-950">
      <div class="w-full max-w-md px-6">
        <h1 class="text-3xl font-bold text-center mb-2 text-zinc-100">NicotinD</h1>
        <p class="text-zinc-500 text-center text-sm mb-8">Initial Setup</p>

        @if (step() !== 'done') {
          <div class="flex items-center gap-2 mb-6 justify-center">
            @for (i of stepDots(); track i) {
              <div class="h-1 rounded-full transition-all w-8"
                [class]="i <= stepNumber() ? 'bg-zinc-100' : 'bg-zinc-800'"
              ></div>
            }
          </div>
        }

        <!-- Step 1: Admin -->
        @if (step() === 'admin') {
          <form (ngSubmit)="handleAdminNext()" class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 class="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-4">Create Admin Account</h2>
              <div class="space-y-3">
                <input type="text" placeholder="Username" [(ngModel)]="adminUsername" name="adminUser" required autofocus
                  class="w-full px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm" />
                <app-password-field [(ngModel)]="adminPassword" name="adminPass" [placeholder]="'Password'" [required]="true" [autocomplete]="'new-password'"
                  [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm'" />
              </div>
            </div>
            @if (error()) { <p class="text-red-400 text-sm">{{ error() }}</p> }
            <button type="submit" [disabled]="!adminUsername.trim() || !adminPassword.trim()"
              class="w-full py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50">
              Next
            </button>
          </form>
        }

        <!-- Step 2: Soulseek -->
        @if (step() === 'soulseek') {
          <div class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 class="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-1">Soulseek Network</h2>
              <p class="text-xs text-zinc-600 mb-4">Connect to Soulseek for P2P music search. You can skip this and configure it later in Settings.</p>
              <div class="flex gap-1 p-1 rounded-lg bg-zinc-800/50 w-fit mb-4">
                <button type="button" (click)="slskIsNewAccount.set(false); slskConfirmPassword = ''; error.set('')"
                  [class]="!slskIsNewAccount() ? 'px-3 py-1.5 rounded-md text-xs font-medium transition bg-zinc-700 text-zinc-100' : 'px-3 py-1.5 rounded-md text-xs font-medium transition text-zinc-400 hover:text-zinc-200'">
                  I have an account
                </button>
                <button type="button" (click)="slskIsNewAccount.set(true); error.set('')"
                  [class]="slskIsNewAccount() ? 'px-3 py-1.5 rounded-md text-xs font-medium transition bg-zinc-700 text-zinc-100' : 'px-3 py-1.5 rounded-md text-xs font-medium transition text-zinc-400 hover:text-zinc-200'">
                  Create new account
                </button>
              </div>
              <div class="space-y-3">
                <input type="text" [placeholder]="slskIsNewAccount() ? 'Choose a username' : 'Soulseek username'" [(ngModel)]="slskUsername" autofocus
                  class="w-full px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm" />
                <app-password-field [(ngModel)]="slskPassword" [placeholder]="slskIsNewAccount() ? 'Choose a password' : 'Soulseek password'" [autocomplete]="'new-password'"
                  [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm'" />
                @if (slskIsNewAccount()) {
                  <app-password-field [(ngModel)]="slskConfirmPassword" [placeholder]="'Confirm password'" [autocomplete]="'new-password'"
                    [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm'" />
                  @if (slskConfirmPassword && slskPassword !== slskConfirmPassword) {
                    <p class="text-xs text-red-400">Passwords do not match</p>
                  }
                }
              </div>
            </div>
            @if (error()) { <p class="text-red-400 text-sm">{{ error() }}</p> }
            <div class="flex gap-3">
              <button (click)="step.set('admin')" class="px-5 py-3 rounded-lg border border-zinc-800 text-zinc-400 text-sm font-medium hover:border-zinc-600 transition">Back</button>
              <button (click)="handleSoulseekNext()" [disabled]="loading()"
                class="flex-1 py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50">
                {{ soulseekButtonLabel() }}
              </button>
            </div>
          </div>
        }

        <!-- Step 3: Tailscale -->
        @if (step() === 'tailscale') {
          <div class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 class="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-1">Tailscale Remote Access</h2>
              <p class="text-xs text-zinc-600 mb-4">Connect to your Tailscale network for secure remote access. You can skip this and configure it later.</p>
              <app-password-field [(ngModel)]="tsAuthKey" [placeholder]="'tskey-auth-...'" [autocomplete]="'off'" autofocus
                [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm font-mono'" />
            </div>
            @if (error()) { <p class="text-red-400 text-sm">{{ error() }}</p> }
            <div class="flex gap-3">
              <button (click)="step.set('soulseek')" class="px-5 py-3 rounded-lg border border-zinc-800 text-zinc-400 text-sm font-medium hover:border-zinc-600 transition">Back</button>
              <button (click)="handleTailscaleNext()" [disabled]="loading()"
                class="flex-1 py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50">
                {{ loading() ? 'Setting up...' : tsAuthKey.trim() ? 'Connect & Complete' : 'Skip & Complete' }}
              </button>
            </div>
          </div>
        }

        <!-- Done -->
        @if (step() === 'done') {
          <div class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6 text-center">
              <div class="w-12 h-12 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto mb-4">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-emerald-400">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              </div>
              <h2 class="text-lg font-semibold text-zinc-100 mb-1">Setup Complete</h2>
              <p class="text-sm text-zinc-500">Your NicotinD instance is ready.</p>
              @if (tsHostname()) {
                <div class="mt-4 p-3 rounded-lg bg-zinc-800/50 border border-zinc-700/50">
                  <p class="text-xs text-zinc-500 mb-1">Tailscale Address</p>
                  <p class="text-sm text-zinc-200 font-mono">{{ tsHostname() }}</p>
                  @if (tsIp()) { <p class="text-xs text-zinc-500 mt-0.5">{{ tsIp() }}</p> }
                </div>
              }
            </div>
            <button (click)="reload()" class="w-full py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition">Get Started</button>
          </div>
        }
      </div>
    </div>
  `,
})
export class SetupComponent {
  private auth = inject(AuthService);
  private api = inject(ApiService);
  private setupService = inject(SetupService);

  readonly step = signal<Step>('admin');
  readonly loading = signal(false);
  readonly error = signal('');
  readonly slskIsNewAccount = signal(false);
  readonly tsHostname = signal('');
  readonly tsIp = signal('');

  adminUsername = '';
  adminPassword = '';
  slskUsername = '';
  slskPassword = '';
  slskConfirmPassword = '';
  tsAuthKey = '';

  private adminData: { username: string; password: string } | null = null;
  private slskData: { username: string; password: string } | null = null;

  get setupStatus(): SetupStatus | null {
    return this.setupService.status();
  }

  stepNumber(): number {
    const s = this.step();
    if (s === 'admin') return 1;
    if (s === 'soulseek') return 2;
    if (s === 'tailscale') return 3;
    return 4;
  }

  stepDots(): number[] {
    const total = this.setupStatus?.tailscale.available ? 3 : 2;
    return Array.from({ length: total }, (_, i) => i + 1);
  }

  soulseekButtonLabel(): string {
    const hasSlsk = this.slskUsername.trim() && this.slskPassword.trim();
    const hasTailscale = this.setupStatus?.tailscale.available;
    if (hasSlsk) return hasTailscale ? 'Next' : 'Complete Setup';
    return hasTailscale ? 'Skip' : 'Skip & Complete';
  }

  handleAdminNext(): void {
    if (!this.adminUsername.trim() || !this.adminPassword.trim()) return;
    this.adminData = { username: this.adminUsername.trim(), password: this.adminPassword.trim() };
    this.error.set('');
    this.step.set('soulseek');
  }

  handleSoulseekNext(): void {
    if (this.slskIsNewAccount() && this.slskPassword !== this.slskConfirmPassword) {
      this.error.set('Passwords do not match');
      return;
    }
    if (this.slskUsername.trim() && this.slskPassword.trim()) {
      this.slskData = { username: this.slskUsername.trim(), password: this.slskPassword.trim() };
    }
    this.error.set('');
    if (this.setupStatus?.tailscale.available) {
      this.step.set('tailscale');
    } else {
      this.submitSetup(this.slskData, null);
    }
  }

  handleTailscaleNext(): void {
    this.submitSetup(this.slskData, this.tsAuthKey.trim() || null);
  }

  private submitSetup(
    soulseek: { username: string; password: string } | null,
    tailscaleKey: string | null,
  ): void {
    if (!this.adminData) return;
    this.loading.set(true);
    this.error.set('');

    this.api.completeSetup({
      admin: this.adminData,
      ...(soulseek ? { soulseek } : {}),
      ...(tailscaleKey ? { tailscale: { authKey: tailscaleKey } } : {}),
    }).subscribe({
      next: (result) => {
        if (result.tailscale.connected && result.tailscale.hostname) {
          this.tsHostname.set(result.tailscale.hostname);
          this.tsIp.set(result.tailscale.ip ?? '');
        }
        this.auth.login(result.token, result.user.username, result.user.role);
        this.step.set('done');
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set(err.error?.error ?? err.message ?? 'Setup failed');
        this.loading.set(false);
      },
    });
  }

  reload(): void {
    window.location.reload();
  }
}


    <div class="min-h-screen flex items-center justify-center bg-zinc-950">
      <div class="w-full max-w-md px-6">
        <h1 class="text-3xl font-bold text-center mb-2 text-zinc-100">NicotinD</h1>
        <p class="text-zinc-500 text-center text-sm mb-8">Initial Setup</p>

        @if (step() !== 'done') {
          <div class="flex items-center gap-2 mb-6 justify-center">
            @for (i of stepDots(); track i) {
              <div class="h-1 rounded-full transition-all w-8"
                [class]="i <= stepNumber() ? 'bg-zinc-100' : 'bg-zinc-800'"
              ></div>
            }
          </div>
        }

        <!-- Step 1: Admin -->
        @if (step() === 'admin') {
          <form (ngSubmit)="handleAdminNext()" class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 class="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-4">Create Admin Account</h2>
              <div class="space-y-3">
                <input type="text" placeholder="Username" [(ngModel)]="adminUsername" name="adminUser" required autofocus
                  data-testid="setup-username"
                  class="w-full px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm" />
                <app-password-field [(ngModel)]="adminPassword" name="adminPass" [placeholder]="'Password'" [required]="true" [autocomplete]="'new-password'"
                  [testId]="'setup-password'"
                  [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm'" />
              </div>
            </div>
            @if (error()) { <p class="text-red-400 text-sm">{{ error() }}</p> }
            <button type="submit" [disabled]="!adminUsername.trim() || !adminPassword.trim()"
              data-testid="setup-submit"
              class="w-full py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50">
              Next
            </button>
          </form>
        }

        <!-- Step 2: Library -->
        @if (step() === 'library') {
          <div class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 class="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-1">Music Library</h2>
              <p class="text-xs text-zinc-600 mb-4">Where your music files live. You can change this later in Settings.</p>
              <div class="space-y-3">
                <div class="flex gap-2">
                  <input type="text" placeholder="Music directory (e.g. ~/Music)" [(ngModel)]="musicDir" name="musicDir" autofocus
                    data-testid="setup-music-dir"
                    class="flex-1 px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm" />
                  @if (isElectron()) {
                    <button type="button" (click)="chooseFolder()" data-testid="onboarding-pick-folder"
                      class="px-4 py-3 rounded-lg border border-zinc-700 text-zinc-300 text-sm font-medium hover:border-zinc-500 transition whitespace-nowrap">Choose folder…</button>
                  }
                </div>
                <p class="text-xs text-zinc-500">Leave blank to use <code class="text-zinc-400">~/Music</code> as the default.</p>
              </div>
            </div>
            @if (error()) { <p class="text-red-400 text-sm">{{ error() }}</p> }
            <div class="flex gap-3">
              <button type="button" (click)="step.set('admin')" class="px-5 py-3 rounded-lg border border-zinc-800 text-zinc-400 text-sm font-medium hover:border-zinc-600 transition">Back</button>
              <button type="button" (click)="handleLibraryNext()" data-testid="setup-next-library"
                class="flex-1 py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition">Next</button>
            </div>
          </div>
        }

        <!-- Step 3: Quality -->
        @if (step() === 'quality') {
          <div class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 class="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-1">Streaming Quality</h2>
              <p class="text-xs text-zinc-600 mb-4">Convert lossless downloads (FLAC, WAV, ALAC) to Opus for smaller files and wider browser compatibility.</p>
              <div class="space-y-4">
                <label class="flex items-center justify-between cursor-pointer">
                  <span class="text-sm text-zinc-300">Convert lossless to Opus</span>
                  <button type="button" (click)="transcodeLosslessEnabled = !transcodeLosslessEnabled"
                    [class]="transcodeLosslessEnabled ? 'bg-emerald-500' : 'bg-zinc-700'"
                    class="relative inline-flex h-6 w-11 items-center rounded-full transition-colors">
                    <span [class.translate-x-5]="transcodeLosslessEnabled" [class.translate-x-1]="!transcodeLosslessEnabled"
                      class="inline-block h-4 w-4 transform rounded-full bg-white transition-transform"></span>
                  </button>
                </label>
                @if (transcodeLosslessEnabled) {
                  <div>
                    <label class="block text-xs text-zinc-500 mb-2">Bitrate</label>
                    <div class="flex gap-2">
                      @for (br of [128, 192, 256]; track br) {
                        <button type="button" (click)="transcodeBitrate = br"
                          [class]="transcodeBitrate === br ? 'bg-zinc-600 text-zinc-100 border-zinc-500' : 'bg-zinc-800 text-zinc-400 border-zinc-700'"
                          class="flex-1 py-2 rounded-lg border text-sm font-medium transition">
                          {{ br }} kbps
                        </button>
                      }
                    </div>
                  </div>
                }
              </div>
            </div>
            @if (error()) { <p class="text-red-400 text-sm">{{ error() }}</p> }
            <div class="flex gap-3">
              <button type="button" (click)="step.set('library')" class="px-5 py-3 rounded-lg border border-zinc-800 text-zinc-400 text-sm font-medium hover:border-zinc-600 transition">Back</button>
              <button type="button" (click)="handleQualityNext()" data-testid="setup-next-quality"
                class="flex-1 py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition">Next</button>
            </div>
          </div>
        }

        <!-- Step 4: Soulseek -->
        @if (step() === 'soulseek') {
          <div class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 class="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-1">Soulseek Network</h2>
              <p class="text-xs text-zinc-600 mb-4">Connect to Soulseek for P2P music search. Soulseek is an optional extension — you can skip this and enable/configure it later under Settings → Extensions.</p>
              <div class="flex gap-1 p-1 rounded-lg bg-zinc-800/50 w-fit mb-4">
                <button type="button" (click)="slskIsNewAccount.set(false); slskConfirmPassword = ''; error.set('')"
                  [class]="!slskIsNewAccount() ? 'px-3 py-1.5 rounded-md text-xs font-medium transition bg-zinc-700 text-zinc-100' : 'px-3 py-1.5 rounded-md text-xs font-medium transition text-zinc-400 hover:text-zinc-200'">
                  I have an account
                </button>
                <button type="button" (click)="slskIsNewAccount.set(true); error.set('')"
                  [class]="slskIsNewAccount() ? 'px-3 py-1.5 rounded-md text-xs font-medium transition bg-zinc-700 text-zinc-100' : 'px-3 py-1.5 rounded-md text-xs font-medium transition text-zinc-400 hover:text-zinc-200'">
                  Create new account
                </button>
              </div>
              <div class="space-y-3">
                <input type="text" [placeholder]="slskIsNewAccount() ? 'Choose a username' : 'Soulseek username'" [(ngModel)]="slskUsername" name="slskUser" autofocus
                  class="w-full px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm" />
                <app-password-field [(ngModel)]="slskPassword" name="slskPass" [placeholder]="slskIsNewAccount() ? 'Choose a password' : 'Soulseek password'" [autocomplete]="'new-password'"
                  [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm'" />
                @if (slskIsNewAccount()) {
                  <app-password-field [(ngModel)]="slskConfirmPassword" name="slskConfirm" [placeholder]="'Confirm password'" [autocomplete]="'new-password'"
                    [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm'" />
                  @if (slskConfirmPassword && slskPassword !== slskConfirmPassword) {
                    <p class="text-xs text-red-400">Passwords do not match</p>
                  }
                }
              </div>
            </div>

            <!-- Advanced: Lidarr -->
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 overflow-hidden">
              <button type="button" (click)="showLidarr.set(!showLidarr())"
                data-testid="setup-advanced-toggle"
                class="w-full flex items-center justify-between p-4 hover:bg-zinc-800/30 transition">
                <span class="text-sm font-semibold uppercase tracking-wider text-zinc-400">Advanced Services</span>
                <svg [class.rotate-180]="showLidarr()" class="w-4 h-4 text-zinc-500 transition-transform" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>
              @if (showLidarr()) {
                <div class="px-4 pb-4 space-y-3">
                  <p class="text-xs text-zinc-600 mb-2">Connect Lidarr for metadata enrichment (artist images, album details, release info). Optional — can be configured later.</p>
                  <input type="text" placeholder="Lidarr URL (e.g. http://localhost:8686)" [(ngModel)]="lidarrUrl" name="lidarrUrl"
                    data-testid="setup-lidarr-url"
                    class="w-full px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm" />
                  <app-password-field [(ngModel)]="lidarrApiKey" name="lidarrApiKey" [placeholder]="'Lidarr API Key'" [autocomplete]="'off'"
                    [testId]="'setup-lidarr-apikey'"
                    [inputClass]="'px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm'" />
                </div>
              }
            </div>

            @if (error()) { <p class="text-red-400 text-sm">{{ error() }}</p> }
            <div class="flex gap-3">
              <button type="button" (click)="step.set('quality')" class="px-5 py-3 rounded-lg border border-zinc-800 text-zinc-400 text-sm font-medium hover:border-zinc-600 transition">Back</button>
              <button type="button" (click)="handleSoulseekNext()" [disabled]="loading()"
                data-testid="setup-soulseek-next"
                class="flex-1 py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50">
                {{ soulseekButtonLabel() }}
              </button>
            </div>
          </div>
        }

        <!-- Done -->
        @if (step() === 'done') {
          <div class="space-y-4">
            <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6 text-center">
              <div class="w-12 h-12 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto mb-4">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-emerald-400">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              </div>
              <h2 class="text-lg font-semibold text-zinc-100 mb-1">Setup Complete</h2>
              <p class="text-sm text-zinc-500">Your NicotinD instance is ready.</p>
              @if (needsRestart()) {
                <p class="text-xs text-amber-400 mt-2">Lidarr will be available after restarting NicotinD.</p>
              }
            </div>
            <button type="button" (click)="enterApp()" [disabled]="loading()" data-testid="setup-done" class="w-full py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-60">{{ loading() ? 'Restarting…' : 'Get Started' }}</button>
          </div>
        }
      </div>
    </div>

// packages/web/src/pages/Setup.tsx
import { useState } from 'react';
import { api, type SetupStatus } from '@/lib/api';
import { useAuthStore } from '@/stores/auth';
import { PasswordField } from '@/components/PasswordField';

interface Props {
  setupStatus: SetupStatus;
}

type Step = 'admin' | 'soulseek' | 'tailscale' | 'done';

export function SetupPage({ setupStatus }: Props) {
  const login = useAuthStore((s) => s.login);

  const [step, setStep] = useState<Step>('admin');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Admin fields
  const [adminUsername, setAdminUsername] = useState('');
  const [adminPassword, setAdminPassword] = useState('');

  // Soulseek fields
  const [slskUsername, setSlskUsername] = useState('');
  const [slskPassword, setSlskPassword] = useState('');
  const [slskConfirmPassword, setSlskConfirmPassword] = useState('');
  const [slskIsNewAccount, setSlskIsNewAccount] = useState(false);

  // Tailscale fields
  const [tsAuthKey, setTsAuthKey] = useState('');

  // Result
  const [tsHostname, setTsHostname] = useState('');
  const [tsIp, setTsIp] = useState('');

  // Collected data for final submit
  const [adminData, setAdminData] = useState<{ username: string; password: string } | null>(null);
  const [slskData, setSlskData] = useState<{ username: string; password: string } | null>(null);

  function handleAdminNext(e: React.FormEvent) {
    e.preventDefault();
    if (!adminUsername.trim() || !adminPassword.trim()) return;
    setAdminData({ username: adminUsername.trim(), password: adminPassword.trim() });
    setError('');
    setStep('soulseek');
  }

  function handleSoulseekNext() {
    if (slskIsNewAccount && slskPassword !== slskConfirmPassword) {
      setError('Passwords do not match');
      return;
    }
    if (slskUsername.trim() && slskPassword.trim()) {
      setSlskData({ username: slskUsername.trim(), password: slskPassword.trim() });
    }
    setError('');
    if (setupStatus.tailscale.available) {
      setStep('tailscale');
    } else {
      submitSetup(slskUsername.trim() && slskPassword.trim()
        ? { username: slskUsername.trim(), password: slskPassword.trim() }
        : null, null);
    }
  }

  function handleTailscaleNext() {
    const tsKey = tsAuthKey.trim() || null;
    submitSetup(slskData, tsKey ? tsKey : null);
  }

  async function submitSetup(
    soulseek: { username: string; password: string } | null,
    tailscaleKey: string | null,
  ) {
    if (!adminData) return;
    setLoading(true);
    setError('');

    try {
      const result = await api.completeSetup({
        admin: adminData,
        ...(soulseek ? { soulseek } : {}),
        ...(tailscaleKey ? { tailscale: { authKey: tailscaleKey } } : {}),
      });

      if (result.tailscale.connected && result.tailscale.hostname) {
        setTsHostname(result.tailscale.hostname);
        setTsIp(result.tailscale.ip ?? '');
      }

      // Store auth
      login(result.token, result.user.username, result.user.role);
      setStep('done');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Setup failed');
    } finally {
      setLoading(false);
    }
  }

  function stepNumber() {
    if (step === 'admin') return 1;
    if (step === 'soulseek') return 2;
    if (step === 'tailscale') return 3;
    return 4;
  }

  const totalSteps = setupStatus.tailscale.available ? 3 : 2;

  return (
    <div className="min-h-screen flex items-center justify-center bg-zinc-950">
      <div className="w-full max-w-md px-6">
        <h1 className="text-3xl font-bold text-center mb-2 text-zinc-100">NicotinD</h1>
        <p className="text-zinc-500 text-center text-sm mb-8">Initial Setup</p>

        {step !== 'done' && (
          <div className="flex items-center gap-2 mb-6 justify-center">
            {Array.from({ length: totalSteps }, (_, i) => (
              <div
                key={i}
                className={`h-1 rounded-full transition-all ${
                  i + 1 <= stepNumber()
                    ? 'w-8 bg-zinc-100'
                    : 'w-8 bg-zinc-800'
                }`}
              />
            ))}
          </div>
        )}

        {/* Step 1: Admin Account */}
        {step === 'admin' && (
          <form onSubmit={handleAdminNext} className="space-y-4">
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-4">
                Create Admin Account
              </h2>
              <div className="space-y-3">
                <input
                  type="text"
                  placeholder="Username"
                  value={adminUsername}
                  onChange={(e) => setAdminUsername(e.target.value)}
                  required
                  autoFocus
                  className="w-full px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm"
                />
                <PasswordField
                  placeholder="Password"
                  value={adminPassword}
                  onChange={(e) => setAdminPassword(e.target.value)}
                  required
                  autoComplete="new-password"
                  inputClassName="px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm"
                />
              </div>
            </div>

            {error && <p className="text-red-400 text-sm">{error}</p>}

            <button
              type="submit"
              disabled={!adminUsername.trim() || !adminPassword.trim()}
              className="w-full py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50"
            >
              Next
            </button>
          </form>
        )}

        {/* Step 2: Soulseek */}
        {step === 'soulseek' && (
          <div className="space-y-4">
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-1">
                Soulseek Network
              </h2>
              <p className="text-xs text-zinc-600 mb-4">
                Connect to Soulseek for P2P music search. You can skip this and configure it later in Settings.
              </p>

              {/* Account mode toggle */}
              <div className="flex gap-1 p-1 rounded-lg bg-zinc-800/50 w-fit mb-4">
                <button
                  type="button"
                  onClick={() => { setSlskIsNewAccount(false); setSlskConfirmPassword(''); setError(''); }}
                  className={`px-3 py-1.5 rounded-md text-xs font-medium transition ${
                    !slskIsNewAccount ? 'bg-zinc-700 text-zinc-100' : 'text-zinc-400 hover:text-zinc-200'
                  }`}
                >
                  I have an account
                </button>
                <button
                  type="button"
                  onClick={() => { setSlskIsNewAccount(true); setError(''); }}
                  className={`px-3 py-1.5 rounded-md text-xs font-medium transition ${
                    slskIsNewAccount ? 'bg-zinc-700 text-zinc-100' : 'text-zinc-400 hover:text-zinc-200'
                  }`}
                >
                  Create new account
                </button>
              </div>

              <div className="space-y-3">
                <input
                  type="text"
                  placeholder={slskIsNewAccount ? 'Choose a username' : 'Soulseek username'}
                  value={slskUsername}
                  onChange={(e) => setSlskUsername(e.target.value)}
                  autoFocus
                  className="w-full px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm"
                />
                <PasswordField
                  placeholder={slskIsNewAccount ? 'Choose a password' : 'Soulseek password'}
                  value={slskPassword}
                  onChange={(e) => setSlskPassword(e.target.value)}
                  autoComplete="new-password"
                  inputClassName="px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm"
                />
                {slskIsNewAccount && (
                  <>
                    <PasswordField
                      placeholder="Confirm password"
                      value={slskConfirmPassword}
                      onChange={(e) => setSlskConfirmPassword(e.target.value)}
                      autoComplete="new-password"
                      inputClassName="px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm"
                    />
                    {slskConfirmPassword && slskPassword !== slskConfirmPassword && (
                      <p className="text-xs text-red-400">Passwords do not match</p>
                    )}
                  </>
                )}
              </div>
            </div>

            {error && <p className="text-red-400 text-sm">{error}</p>}

            <div className="flex gap-3">
              <button
                onClick={() => setStep('admin')}
                className="px-5 py-3 rounded-lg border border-zinc-800 text-zinc-400 text-sm font-medium hover:border-zinc-600 transition"
              >
                Back
              </button>
              <button
                onClick={handleSoulseekNext}
                disabled={loading}
                className="flex-1 py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50"
              >
                {slskUsername.trim() && slskPassword.trim()
                  ? setupStatus.tailscale.available ? 'Next' : 'Complete Setup'
                  : setupStatus.tailscale.available ? 'Skip' : 'Skip & Complete'}
              </button>
            </div>
          </div>
        )}

        {/* Step 3: Tailscale */}
        {step === 'tailscale' && (
          <div className="space-y-4">
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-400 mb-1">
                Tailscale Remote Access
              </h2>
              <p className="text-xs text-zinc-600 mb-4">
                Connect to your Tailscale network for secure remote access from your phone.
                Get an auth key from your Tailscale admin console. You can skip this and configure it later.
              </p>
              <PasswordField
                placeholder="tskey-auth-..."
                value={tsAuthKey}
                onChange={(e) => setTsAuthKey(e.target.value)}
                autoFocus
                autoComplete="off"
                inputClassName="px-4 py-3 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-500 transition text-sm font-mono"
              />
            </div>

            {error && <p className="text-red-400 text-sm">{error}</p>}

            <div className="flex gap-3">
              <button
                onClick={() => setStep('soulseek')}
                className="px-5 py-3 rounded-lg border border-zinc-800 text-zinc-400 text-sm font-medium hover:border-zinc-600 transition"
              >
                Back
              </button>
              <button
                onClick={handleTailscaleNext}
                disabled={loading}
                className="flex-1 py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition disabled:opacity-50"
              >
                {loading ? 'Setting up...' : tsAuthKey.trim() ? 'Connect & Complete' : 'Skip & Complete'}
              </button>
            </div>
          </div>
        )}

        {/* Done */}
        {step === 'done' && (
          <div className="space-y-4">
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6 text-center">
              <div className="w-12 h-12 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto mb-4">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-emerald-400">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              </div>
              <h2 className="text-lg font-semibold text-zinc-100 mb-1">Setup Complete</h2>
              <p className="text-sm text-zinc-500">Your NicotinD instance is ready.</p>

              {tsHostname && (
                <div className="mt-4 p-3 rounded-lg bg-zinc-800/50 border border-zinc-700/50">
                  <p className="text-xs text-zinc-500 mb-1">Tailscale Address</p>
                  <p className="text-sm text-zinc-200 font-mono">{tsHostname}</p>
                  {tsIp && <p className="text-xs text-zinc-500 mt-0.5">{tsIp}</p>}
                </div>
              )}
            </div>

            <button
              onClick={() => window.location.reload()}
              className="w-full py-3 rounded-lg bg-zinc-100 text-zinc-900 font-semibold hover:bg-zinc-200 transition"
            >
              Get Started
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
