// packages/web/src/app/components/player/player.component.ts
import {
  Component,
  inject,
  signal,
  computed,
  effect,
  viewChild,
  ElementRef,
  OnDestroy,
  AfterViewInit,
  NgZone,
} from '@angular/core';
import { Router } from '@angular/router';
import { PlayerService } from '../../services/player.service';
import { AuthService } from '../../services/auth.service';
import { RemotePlaybackService } from '../../services/remote-playback.service';
import { PlaybackWsService } from '../../services/playback-ws.service';
import { CoverArtComponent } from '../cover-art/cover-art.component';
import { DeviceSwitcherComponent } from '../device-switcher/device-switcher.component';
import { PreserveService } from '../../services/preserve.service';
import * as db from '../../lib/preserve-store';

/** Returns the router commands to navigate to an artist page, or to /library as fallback. */
export function resolveArtistRoute(artistId: string | undefined): string[] {
  return artistId ? ['/library/artists', artistId] : ['/library'];
}

function formatTime(s: number): string {
  if (!Number.isFinite(s) || s < 0) return '0:00';
  const m = Math.floor(s / 60);
  const sec = Math.floor(s % 60);
  return `${m}:${sec.toString().padStart(2, '0')}`;
}

@Component({
  selector: 'app-player',
  imports: [CoverArtComponent, DeviceSwitcherComponent],
  templateUrl: './player.component.html',
  })
export class PlayerComponent implements AfterViewInit, OnDestroy {
  readonly player = inject(PlayerService);
  readonly auth = inject(AuthService);
  private remote = inject(RemotePlaybackService);
  private ws = inject(PlaybackWsService);
  private router = inject(Router);
  private zone = inject(NgZone);
  private preserve = inject(PreserveService);

  private audioEl = viewChild<ElementRef<HTMLAudioElement>>('audioEl');

  private pausingByStore = false;
  private progressReportInterval: ReturnType<typeof setInterval> | null = null;
  private rafId: number | null = null;

  // Playback progress interpolation
  private interpolatedTime = signal(0);

  readonly isActiveDevice = this.remote.isActiveDevice;

  readonly displayTime = computed(() => {
    if (this.isActiveDevice()) return this.player.currentTime();
    return this.interpolatedTime();
  });

  readonly displayDuration = computed(() => {
    if (this.isActiveDevice()) return this.player.duration();
    return this.remote.remoteDuration() || this.player.duration();
  });

  readonly safeDuration = computed(() => {
    const d = this.displayDuration();
    return Number.isFinite(d) && d > 0 ? d : 0;
  });

  readonly safeProgress = computed(() => {
    const t = this.displayTime();
    const d = this.safeDuration();
    return Number.isFinite(t) && t >= 0 ? Math.min(t, d || t) : 0;
  });

  readonly progressPercent = computed(() => {
    const d = this.safeDuration();
    return d > 0 ? Math.max(0, Math.min(100, (this.safeProgress() / d) * 100)) : 0;
  });

  readonly showPlaying = computed(() => {
    return this.isActiveDevice() ? this.player.isPlaying() : this.remote.remoteIsPlaying();
  });

  // Event listener teardown references
  private audioListenerCleanups: (() => void)[] = [];

  constructor() {
    // Effect 1: Load track (checks IndexedDB first for offline-preserved tracks)
    effect((onCleanup) => {
      const track = this.player.currentTrack();
      const token = this.auth.token();
      const isActive = this.isActiveDevice();
      const audio = this.audioEl()?.nativeElement;
      if (!audio) return;

      let objectUrl: string | null = null;
      onCleanup(() => {
        if (objectUrl) URL.revokeObjectURL(objectUrl);
      });

      if (!isActive) {
        this.pausingByStore = true;
        audio.pause();
        this.pausingByStore = false;
        audio.src = '';
        return;
      }

      if (track) {
        this.player.setCurrentTime(0);
        this.player.setDuration(track.duration ?? 0);

        if (this.preserve.isPreserved(track.id)) {
          // Load from IndexedDB — no network request
          (async () => {
            const blob = await db.getBlob(track.id);
            if (blob) {
              objectUrl = URL.createObjectURL(blob.audio);
              audio.src = objectUrl;
              db.updateLastAccessed(track.id);
            } else {
              // Metadata exists but blob missing — fall back to stream
              audio.src = `/api/stream/${track.id}?token=${token}`;
            }
            audio.play().catch((err) => {
              if (err.name === 'NotAllowedError') this.player.setAutoplayBlocked(true);
            });
          })();
        } else {
          audio.src = `/api/stream/${track.id}?token=${token}`;
          audio.play().catch((err) => {
            if (err.name === 'NotAllowedError') this.player.setAutoplayBlocked(true);
          });
        }
      } else {
        this.pausingByStore = true;
        audio.pause();
        this.pausingByStore = false;
        audio.src = '';
        this.player.setCurrentTime(0);
        this.player.setDuration(0);
      }
    });

    // Effect 2: Media Session metadata
    effect(() => {
      const track = this.player.currentTrack();
      const token = this.auth.token();
      if (!('mediaSession' in navigator)) return;

      if (!track) {
        navigator.mediaSession.metadata = null;
        navigator.mediaSession.playbackState = 'none';
        return;
      }

      navigator.mediaSession.metadata = new MediaMetadata({
        title: track.title,
        artist: track.artist,
        album: track.album ?? '',
        artwork: track.coverArt
          ? [
              { src: `/api/cover/${track.coverArt}?size=96&token=${token}`, sizes: '96x96', type: 'image/jpeg' },
              { src: `/api/cover/${track.coverArt}?size=256&token=${token}`, sizes: '256x256', type: 'image/jpeg' },
              { src: `/api/cover/${track.coverArt}?size=512&token=${token}`, sizes: '512x512', type: 'image/jpeg' },
            ]
          : [],
      });
    });

    // Effect 3: Media Session playback state
    effect(() => {
      const playing = this.player.isPlaying();
      if (!('mediaSession' in navigator)) return;
      navigator.mediaSession.playbackState = playing ? 'playing' : 'paused';
    });

    // Effect 4: Media Session action handlers
    effect(() => {
      const queue = this.player.queue();
      const history = this.player.history();
      const repeat = this.player.repeat();
      if (!('mediaSession' in navigator)) return;

      const canGoNext = queue.length > 0 || repeat === 'all' || repeat === 'one';
      const canGoPrev = history.length > 0;

      navigator.mediaSession.setActionHandler('play', () => this.player.resume());
      navigator.mediaSession.setActionHandler('pause', () => this.player.pause());
      navigator.mediaSession.setActionHandler(
        'nexttrack',
        canGoNext ? () => this.player.playNext() : null,
      );
      navigator.mediaSession.setActionHandler(
        'previoustrack',
        canGoPrev
          ? () => {
              const audio = this.audioEl()?.nativeElement;
              if (audio && audio.currentTime > 3) {
                audio.currentTime = 0;
              } else {
                this.player.playPrev();
              }
            }
          : null,
      );
      navigator.mediaSession.setActionHandler('seekto', (details) => {
        if (details.seekTime != null) this.player.seek(details.seekTime);
      });
      navigator.mediaSession.setActionHandler('seekforward', () => {
        this.player.seek(this.player.currentTime() + 10);
      });
      navigator.mediaSession.setActionHandler('seekbackward', () => {
        this.player.seek(Math.max(0, this.player.currentTime() - 10));
      });
    });

    // Effect 5: Play/pause sync
    effect(() => {
      const playing = this.player.isPlaying();
      const isActive = this.isActiveDevice();
      const audio = this.audioEl()?.nativeElement;
      if (!audio) return;

      if (!isActive) {
        this.pausingByStore = true;
        audio.pause();
        this.pausingByStore = false;
        return;
      }
      if (playing) {
        audio.play().catch((err) => {
          if (err.name === 'NotAllowedError') this.player.setAutoplayBlocked(true);
        });
      } else {
        this.pausingByStore = true;
        audio.pause();
        this.pausingByStore = false;
      }
    });

    // Effect 6: Seek from store
    effect(() => {
      const seekTo = this.player.seekTo();
      const audio = this.audioEl()?.nativeElement;
      if (!audio || seekTo === null) return;
      audio.currentTime = seekTo;
      this.player.clearSeek();
    });

    // Effect 7: Progress reporting interval
    effect((onCleanup) => {
      const isActive = this.isActiveDevice();
      const playing = this.player.isPlaying();

      if (!isActive || !playing) return;
      const audio = this.audioEl()?.nativeElement;
      if (!audio) return;

      const report = () => {
        if (audio.duration > 0 && Number.isFinite(audio.currentTime)) {
          this.ws.sendProgressReport(audio.currentTime, audio.duration);
        }
      };

      report();
      const interval = setInterval(report, 2000);
      onCleanup(() => clearInterval(interval));
    });

    // Effect 8: Remote playback interpolation (rAF loop)
    effect((onCleanup) => {
      const isActive = this.isActiveDevice();

      if (isActive) {
        this.interpolatedTime.set(this.player.currentTime());
        return;
      }

      const remPlaying = this.remote.remoteIsPlaying();
      const remPos = this.remote.remotePosition();
      const remPosTs = this.remote.remotePositionTs();
      const remDur = this.remote.remoteDuration();

      if (!remPlaying) {
        this.interpolatedTime.set(remPos);
        return;
      }

      let rafId: number;
      const tick = () => {
        const elapsed = (Date.now() - remPosTs) / 1000;
        const maxTime = remDur || Infinity;
        this.interpolatedTime.set(Math.min(remPos + elapsed, maxTime));
        rafId = requestAnimationFrame(tick);
      };
      rafId = requestAnimationFrame(tick);
      onCleanup(() => cancelAnimationFrame(rafId));
    });
  }

  ngAfterViewInit(): void {
    const audio = this.audioEl()?.nativeElement;
    if (!audio) return;

    const onTime = () => {
      const value = audio.currentTime;
      if (Number.isFinite(value) && value >= 0) {
        this.player.setCurrentTime(value);
        if ('mediaSession' in navigator && audio.duration > 0 && Number.isFinite(audio.duration)) {
          try {
            navigator.mediaSession.setPositionState({
              duration: audio.duration,
              playbackRate: 1,
              position: value,
            });
          } catch {
            // Older WebKit may throw
          }
        }
      }
    };
    const onDuration = () => {
      const value = audio.duration;
      if (Number.isFinite(value) && value > 0) this.player.setDuration(value);
    };
    const onEnded = () => this.player.playNext();
    const onPlay = () => {
      this.player.setAutoplayBlocked(false);
      if (!this.player.isPlaying()) {
        this.player.resume();
      }
    };
    const onPause = () => {
      if (this.pausingByStore) return;
      if (this.player.isPlaying()) {
        this.player.pause();
      }
    };

    audio.addEventListener('timeupdate', onTime);
    audio.addEventListener('loadedmetadata', onDuration);
    audio.addEventListener('durationchange', onDuration);
    audio.addEventListener('ended', onEnded);
    audio.addEventListener('play', onPlay);
    audio.addEventListener('pause', onPause);

    this.audioListenerCleanups = [
      () => audio.removeEventListener('timeupdate', onTime),
      () => audio.removeEventListener('loadedmetadata', onDuration),
      () => audio.removeEventListener('durationchange', onDuration),
      () => audio.removeEventListener('ended', onEnded),
      () => audio.removeEventListener('play', onPlay),
      () => audio.removeEventListener('pause', onPause),
    ];
  }

  ngOnDestroy(): void {
    this.audioListenerCleanups.forEach((fn) => fn());
    if (this.progressReportInterval) clearInterval(this.progressReportInterval);
    if (this.rafId) cancelAnimationFrame(this.rafId);
  }

  handlePlayPause(): void {
    if (this.isActiveDevice()) {
      if (this.player.isPlaying()) this.player.pause();
      else this.player.resume();
    } else {
      this.ws.sendCommand(this.remote.remoteIsPlaying() ? 'PAUSE' : 'PLAY');
    }
  }

  handleNext(): void {
    if (this.isActiveDevice()) this.player.playNext();
    else this.ws.sendCommand('NEXT');
  }

  handlePrev(): void {
    const audio = this.audioEl()?.nativeElement;
    if (this.isActiveDevice()) {
      if (audio && audio.currentTime > 3) {
        audio.currentTime = 0;
      } else {
        this.player.playPrev();
      }
    } else {
      this.ws.sendCommand('PREV');
    }
  }

  handleSeek(event: MouseEvent): void {
    const audio = this.audioEl()?.nativeElement;
    const safeDur = this.safeDuration();
    if (!safeDur) return;

    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    if (!rect.width) return;
    const pct = (event.clientX - rect.left) / rect.width;
    const newTime = Math.max(0, Math.min(1, pct)) * safeDur;

    if (this.isActiveDevice() && audio) {
      audio.currentTime = newTime;
    } else {
      this.ws.sendCommand('SEEK', { position: newTime });
      this.remote.setRemoteProgress(newTime, safeDur);
    }
  }

  openNowPlaying(event: MouseEvent): void {
    if ((event.target as HTMLElement).closest('button')) return;
    this.player.setNowPlayingOpen(true);
  }

  navigateToArtist(event: MouseEvent): void {
    event.stopPropagation();
    const track = this.player.currentTrack();
    if (!track) return;
    this.router.navigate(resolveArtistRoute(track.artistId));
  }

  unblockAutoplay(): void {
    const audio = this.audioEl()?.nativeElement;
    if (audio) {
      audio
        .play()
        .then(() => this.player.setAutoplayBlocked(false))
        .catch(() => {});
    }
  }

  formatTime(s: number): string {
    return formatTime(s);
  }
}


    <audio #audioElA></audio>
    <audio #audioElB></audio>
    <!-- Mobile: floats above the fixed bottom tab bar (h-14 + safe-area inset); desktop: bottom-0 (no tab bar).
         Show/hide geometry lives in lib/player-chrome.ts — the hidden state must clear the tab bar too. -->
    <div data-bottom-chrome [class]="'fixed bottom-[calc(3.5rem+env(safe-area-inset-bottom))] md:bottom-0 left-0 right-0 bg-theme-surface border-t border-theme z-50 transition-transform duration-300 ease-out ' +
      slideClass()">

      <!-- Autoplay blocked banner -->
      @if (player.autoplayBlocked()) {
        <div
          class="absolute inset-0 bg-theme-surface/95 flex items-center justify-center z-10 cursor-pointer"
          (click)="unblockAutoplay()"
        >
          <div class="flex items-center gap-3 px-4">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="text-status-warn flex-shrink-0">
              <circle cx="12" cy="12" r="10" />
              <polygon points="10,8 16,12 10,16" fill="currentColor" />
            </svg>
            <span class="text-sm text-theme-secondary">{{ 'player.tapToStart' | t }}</span>
          </div>
        </div>
      }

      <!-- Grab handle ("notch") — pull up / tap to open Now Playing. Wired to the
           same open gesture as the bar so the visible hatch is actually draggable
           (it had no handler before); `touch-none` keeps the browser from
           reclaiming the vertical swipe as a page scroll. The hatch is a solid,
           full-opacity pill (was a faint 4px `/60` bar that read as invisible at
           the bottom of the screen — the user couldn't tell the player was
           draggable). -->
      <div
        class="flex justify-center pt-2.5 pb-1.5 touch-none select-none cursor-pointer"
        data-testid="player-grab"
        (pointerdown)="onBarPointerDown($event)"
      >
        <div class="w-10 h-1.5 rounded-full bg-theme-muted"></div>
      </div>

      <!-- Tap / swipe-up to open Now Playing -->
      <div
        class="flex items-center px-3 md:px-4 gap-2 md:gap-4 h-14 cursor-pointer touch-pan-y"
        (pointerdown)="onBarPointerDown($event)"
      >
        <!-- Track info — mobile: the only growing column (flex-1), so it fills the
             bar and pushes the controls to the right edge (two-column layout);
             desktop: fixed width. -->
        <div class="flex items-center gap-3 min-w-0 flex-1 md:flex-none md:w-60">
          @if (player.currentTrack(); as track) {
            <app-cover-art
              [src]="track.coverArt ? '/api/cover/' + track.coverArt + '?size=80&token=' + auth.token() : undefined"
              [artist]="track.artist"
              [album]="track.album ?? ''"
              [size]="40"
              rounded="rounded"
            />
          }
          <div class="min-w-0 no-callout" translate="no">
            <p class="text-sm font-medium text-theme-primary truncate" data-testid="player-title">{{ player.currentTrack()?.title }}</p>
            <p class="text-xs text-theme-secondary truncate">
              @if (player.currentTrack()?.artists?.length) {
                <app-artist-links [artists]="player.currentTrack()!.artists!" />
              } @else {
                {{ player.currentTrack()?.artist }}
              }
            </p>
          </div>
        </div>

        <!-- Controls — mobile: content-sized, sits at the right edge after the
             track-info column grows; desktop: flex-1 to host the progress bar. -->
        <div class="flex-none md:flex-1 flex flex-col items-center gap-1">
          <div class="flex items-center gap-2 md:gap-3" appTvNavGroup axis="horizontal">
            <!-- Shuffle - desktop only -->
            <button
              (click)="player.toggleShuffle()"
              data-testid="player-shuffle"
              [attr.data-active]="player.shuffle()"
              [class]="'hidden md:flex w-7 h-7 items-center justify-center rounded-full transition ' +
                (player.shuffle() ? 'text-status-done' : 'text-theme-muted hover:text-theme-secondary')"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M16 3h5v5" />
                <path d="M4 20 21 3" />
                <path d="M21 16v5h-5" />
                <path d="M15 15l6 6" />
                <path d="M4 4l5 5" />
              </svg>
            </button>

            <!-- Previous -->
            <button
              appTvNavItem
              (click)="handlePrev()"
              data-testid="player-prev"
              class="w-7 h-7 flex items-center justify-center text-theme-secondary hover:text-theme-primary transition"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <rect x="3" y="5" width="3" height="14" />
                <polygon points="21,5 9,12 21,19" />
              </svg>
            </button>

            <!-- Play/Pause -->
            <button
              appTvNavItem
              (click)="handlePlayPause()"
              data-testid="player-playpause"
              [attr.data-playing]="showPlaying()"
              [attr.data-buffering]="showBuffering()"
              class="w-8 h-8 rounded-full bg-theme-inverse text-theme-inverse flex items-center justify-center hover:opacity-90 transition"
            >
              @if (showBuffering()) {
                <span class="inline-block w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin"></span>
              } @else if (showPlaying()) {
                <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                  <rect x="6" y="4" width="4" height="16" />
                  <rect x="14" y="4" width="4" height="16" />
                </svg>
              } @else {
                <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                  <polygon points="5,3 19,12 5,21" />
                </svg>
              }
            </button>

            <!-- Next -->
            <button
              appTvNavItem
              (click)="handleNext()"
              data-testid="player-next"
              class="w-7 h-7 flex items-center justify-center text-theme-secondary hover:text-theme-primary transition"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <polygon points="3,5 15,12 3,19" />
                <rect x="18" y="5" width="3" height="14" />
              </svg>
            </button>

            <!-- Repeat - desktop only -->
            <button
              (click)="player.cycleRepeat()"
              [class]="'hidden md:flex w-7 h-7 items-center justify-center rounded-full transition relative ' +
                (player.repeat() !== 'off' ? 'text-status-done' : 'text-theme-muted hover:text-theme-secondary')"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M17 2l4 4-4 4" />
                <path d="M3 11v-1a4 4 0 014-4h14" />
                <path d="M7 22l-4-4 4-4" />
                <path d="M21 13v1a4 4 0 01-4 4H3" />
              </svg>
              @if (player.repeat() === 'one') {
                <span class="absolute -top-1 -right-1 text-[9px] font-bold text-status-done">1</span>
              }
            </button>
          </div>

          <!-- Progress bar (desktop) -->
          <div class="hidden md:flex items-center gap-2 w-full max-w-md">
            <span class="text-xs text-theme-muted w-10 text-right">{{ formatTime(safeProgress()) }}</span>
            <div class="flex-1" data-seek data-testid="player-seek">
              <app-seek-bar
                [position]="safeProgress()"
                [duration]="safeDuration()"
                [buffered]="player.bufferedRanges()"
                (seek)="onSeek($event)"
              />
            </div>
            <span class="text-xs text-theme-muted w-10">{{ formatTime(safeDuration()) }}</span>
          </div>
        </div>

        <!-- Right side: device switcher — content-sized on every breakpoint, so it
             takes no space when the switcher is hidden (no empty third column). -->
        <div class="flex items-center justify-end md:flex-none md:flex-shrink-0">
          @if (remote.remoteEnabled()) {
            <app-device-switcher />
          }
        </div>
      </div>

      <!-- Mobile progress bar — native range seek (app-seek-bar). Sits inside the
           player, above the tab bar; its data-seek attr keeps the swipe-to-open
           gesture (onBarPointerDown) from hijacking a scrub. -->
      <div class="md:hidden px-3 pb-1 -mt-1">
        <app-seek-bar
          [position]="safeProgress()"
          [duration]="safeDuration()"
          [buffered]="player.bufferedRanges()"
          (seek)="onSeek($event)"
        />
      </div>
    </div>

// packages/web/src/components/Player.tsx
import { useRef, useEffect, useCallback } from 'react';
import { usePlayerStore } from '@/stores/player';
import { useAuthStore } from '@/stores/auth';
import { PreserveButton } from '@/components/PreserveButton';
import { DeviceSwitcher } from '@/components/DeviceSwitcher';
import { useRemotePlaybackStore } from '@/stores/remote-playback';
import { wsClient } from '@/services/ws-client';
import { useNavigateAndSearch } from '@/hooks/useNavigateAndSearch';
import { usePlaybackProgress } from '@/hooks/usePlaybackProgress';

export function Player() {
  const {
    currentTrack,
    isPlaying,
    pause,
    resume,
    playNext,
    playPrev,
    shuffle,
    toggleShuffle,
    repeat,
    cycleRepeat,
    setCurrentTime,
    setDuration,
    currentTime,
    duration,
    seekTo,
    clearSeek,
    setNowPlayingOpen,
    queue,
    history,
    autoplayBlocked,
    setAutoplayBlocked,
  } = usePlayerStore();
  const token = useAuthStore((s) => s.token);
  const navigateAndSearch = useNavigateAndSearch();
  const { activeDeviceId, remoteIsPlaying } = useRemotePlaybackStore();
  const myId = wsClient.getDeviceId();
  const isActiveDevice = !activeDeviceId || activeDeviceId === myId;
  const audioRef = useRef<HTMLAudioElement>(null);
  const { displayTime, displayDuration } = usePlaybackProgress();

  // Load track
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    if (currentTrack) {
      setCurrentTime(0);
      setDuration(currentTrack.duration ?? 0);
      audio.src = `/api/stream/${currentTrack.id}?token=${token}`;
      audio.play().catch((err) => {
        if (err.name === 'NotAllowedError') setAutoplayBlocked(true);
      });
    } else {
      audio.pause();
      audio.src = '';
      setCurrentTime(0);
      setDuration(0);
    }
  }, [currentTrack, token, setCurrentTime, setDuration]);

  // Media Session: update metadata when track changes
  useEffect(() => {
    if (!('mediaSession' in navigator)) return;

    if (!currentTrack) {
      navigator.mediaSession.metadata = null;
      navigator.mediaSession.playbackState = 'none';
      return;
    }

    navigator.mediaSession.metadata = new MediaMetadata({
      title: currentTrack.title,
      artist: currentTrack.artist,
      album: currentTrack.album ?? '',
      artwork: currentTrack.coverArt
        ? [
            { src: `/api/cover/${currentTrack.coverArt}?size=96&token=${token}`, sizes: '96x96', type: 'image/jpeg' },
            { src: `/api/cover/${currentTrack.coverArt}?size=256&token=${token}`, sizes: '256x256', type: 'image/jpeg' },
            { src: `/api/cover/${currentTrack.coverArt}?size=512&token=${token}`, sizes: '512x512', type: 'image/jpeg' },
          ]
        : [],
    });
  }, [currentTrack, token]);

  // Media Session: sync playback state
  useEffect(() => {
    if (!('mediaSession' in navigator)) return;
    navigator.mediaSession.playbackState = isPlaying ? 'playing' : 'paused';
  }, [isPlaying]);

  // Media Session: action handlers + conditional next/prev
  useEffect(() => {
    if (!('mediaSession' in navigator)) return;

    const canGoNext = queue.length > 0 || repeat === 'all' || repeat === 'one';
    const canGoPrev = history.length > 0;

    navigator.mediaSession.setActionHandler('play', () => usePlayerStore.getState().resume());
    navigator.mediaSession.setActionHandler('pause', () => usePlayerStore.getState().pause());
    navigator.mediaSession.setActionHandler('nexttrack', canGoNext
      ? () => usePlayerStore.getState().playNext()
      : null
    );
    navigator.mediaSession.setActionHandler('previoustrack', canGoPrev
      ? () => {
          const audio = audioRef.current;
          if (audio && audio.currentTime > 3) {
            audio.currentTime = 0;
          } else {
            usePlayerStore.getState().playPrev();
          }
        }
      : null
    );
    navigator.mediaSession.setActionHandler('seekto', (details) => {
      if (details.seekTime != null) usePlayerStore.getState().seek(details.seekTime);
    });
    navigator.mediaSession.setActionHandler('seekforward', () => {
      const current = usePlayerStore.getState().currentTime;
      usePlayerStore.getState().seek(current + 10);
    });
    navigator.mediaSession.setActionHandler('seekbackward', () => {
      const current = usePlayerStore.getState().currentTime;
      usePlayerStore.getState().seek(Math.max(0, current - 10));
    });
  }, [queue, history, repeat]);

  // Play/pause sync — only drive <audio> if we are the active device.
  // Pause immediately when going inactive so host audio stops.
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    console.debug('[Player] play/pause sync: isActiveDevice=', isActiveDevice, 'isPlaying=', isPlaying);
    if (!isActiveDevice) { console.debug('[Player] → audio.pause() (not active)'); audio.pause(); return; }
    if (isPlaying) {
      console.debug('[Player] → audio.play()');
      audio.play().catch((err) => {
        if (err.name === 'NotAllowedError') setAutoplayBlocked(true);
      });
    } else {
      console.debug('[Player] → audio.pause()');
      audio.pause();
    }
  }, [isPlaying, isActiveDevice]);

  // Seek from store
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio || seekTo === null) return;
    audio.currentTime = seekTo;
    clearSeek();
  }, [seekTo, clearSeek]);

  // Audio events
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    const onTime = () => {
      const value = audio.currentTime;
      if (Number.isFinite(value) && value >= 0) {
        setCurrentTime(value);
        // After setCurrentTime(value):
        if ('mediaSession' in navigator && audio.duration > 0 && Number.isFinite(audio.duration)) {
          try {
            navigator.mediaSession.setPositionState({
              duration: audio.duration,
              playbackRate: 1,
              position: value,
            });
          } catch {
            // Older WebKit may throw — silently ignore
          }
        }
      }
    };
    const onDuration = () => {
      const value = audio.duration;
      if (Number.isFinite(value) && value > 0) setDuration(value);
    };
    const onEnded = () => playNext();
    const onPlay = () => setAutoplayBlocked(false);

    audio.addEventListener('timeupdate', onTime);
    audio.addEventListener('loadedmetadata', onDuration);
    audio.addEventListener('durationchange', onDuration);
    audio.addEventListener('ended', onEnded);
    audio.addEventListener('play', onPlay);
    return () => {
      audio.removeEventListener('timeupdate', onTime);
      audio.removeEventListener('loadedmetadata', onDuration);
      audio.removeEventListener('durationchange', onDuration);
      audio.removeEventListener('ended', onEnded);
      audio.removeEventListener('play', onPlay);
    };
  }, [playNext, setCurrentTime, setDuration, setAutoplayBlocked]);

  // Periodic progress reporting — active device tells server its position
  useEffect(() => {
    console.debug('[Player] progress report effect: isActiveDevice=', isActiveDevice, 'isPlaying=', isPlaying);
    if (!isActiveDevice || !isPlaying) return;
    const audio = audioRef.current;
    if (!audio) return;

    const report = () => {
      if (audio.duration > 0 && Number.isFinite(audio.currentTime)) {
        console.debug('[Player] PROGRESS_REPORT →', audio.currentTime.toFixed(1), '/', audio.duration.toFixed(1));
        wsClient.sendProgressReport(audio.currentTime, audio.duration);
      }
    };

    report(); // send one immediately
    const interval = setInterval(report, 2000);
    return () => clearInterval(interval);
  }, [isActiveDevice, isPlaying]);

  const handlePlayPause = useCallback(() => {
    if (isActiveDevice) {
      if (isPlaying) pause();
      else resume();
    } else {
      // Use remoteIsPlaying (server state) not local isPlaying to avoid sending wrong command
      wsClient.sendCommand(remoteIsPlaying ? 'PAUSE' : 'PLAY');
    }
  }, [isActiveDevice, isPlaying, remoteIsPlaying, pause, resume]);

  const handleNext = useCallback(() => {
    if (isActiveDevice) playNext();
    else wsClient.sendCommand('NEXT');
  }, [isActiveDevice, playNext]);

  const handleSeek = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      const audio = audioRef.current;
      const safeDur = Number.isFinite(displayDuration) && displayDuration > 0 ? displayDuration : 0;
      if (!safeDur) return;

      const rect = e.currentTarget.getBoundingClientRect();
      if (!rect.width) return;
      const pct = (e.clientX - rect.left) / rect.width;
      const newTime = Math.max(0, Math.min(1, pct)) * safeDur;

      if (isActiveDevice && audio) {
        audio.currentTime = newTime;
      } else {
        wsClient.sendCommand('SEEK', { position: newTime });
        // Optimistic update so controller seek bar jumps immediately
        useRemotePlaybackStore.getState().setRemoteProgress(newTime, safeDur);
      }
    },
    [displayDuration, isActiveDevice],
  );

  const handlePrev = useCallback(() => {
    const audio = audioRef.current;
    if (isActiveDevice) {
      if (audio && audio.currentTime > 3) {
        audio.currentTime = 0;
      } else {
        playPrev();
      }
    } else {
      wsClient.sendCommand('PREV');
    }
  }, [isActiveDevice, playPrev]);

  function formatTime(s: number) {
    if (!Number.isFinite(s) || s < 0) return '0:00';
    const m = Math.floor(s / 60);
    const sec = Math.floor(s % 60);
    return `${m}:${sec.toString().padStart(2, '0')}`;
  }

  const safeDuration = Number.isFinite(displayDuration) && displayDuration > 0 ? displayDuration : 0;
  const safeProgress =
    Number.isFinite(displayTime) && displayTime >= 0
      ? Math.min(displayTime, safeDuration || displayTime)
      : 0;
  const progressPercent =
    safeDuration > 0 ? Math.max(0, Math.min(100, (safeProgress / safeDuration) * 100)) : 0;

  return (
    <>
      <audio ref={audioRef} />
      <div className={`fixed bottom-0 left-0 right-0 bg-zinc-900 border-t border-zinc-800 z-50 relative transition-transform duration-300 ease-out ${
        currentTrack ? 'translate-y-0' : 'translate-y-full'
      }`}>
        {/* Autoplay blocked banner */}
        {autoplayBlocked && (
          <div
            className="absolute inset-0 bg-zinc-900/95 flex items-center justify-center z-10 cursor-pointer"
            onClick={() => {
              const audio = audioRef.current;
              if (audio) {
                audio.play().then(() => setAutoplayBlocked(false)).catch(() => {});
              }
            }}
          >
            <div className="flex items-center gap-3 px-4">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-amber-400 flex-shrink-0">
                <circle cx="12" cy="12" r="10" />
                <polygon points="10,8 16,12 10,16" fill="currentColor" />
              </svg>
              <span className="text-sm text-zinc-300">Tap here to start playback</span>
            </div>
          </div>
        )}
        {/* Clickable area to open Now Playing */}
        <div
          className="flex items-center px-3 md:px-4 gap-2 md:gap-4 h-16 md:h-18 cursor-pointer"
          onClick={(e) => {
            // Only open panel if clicking the background, not buttons
            if ((e.target as HTMLElement).closest('button')) return;
            setNowPlayingOpen(true);
          }}
        >
          {/* Track info */}
          <div className="flex items-center gap-3 min-w-0 flex-shrink md:w-60 md:flex-shrink-0">
            {currentTrack?.coverArt && (
              <img
                src={`/api/cover/${currentTrack.coverArt}?size=80&token=${token}`}
                alt=""
                className="w-10 h-10 rounded object-cover flex-shrink-0"
              />
            )}
            <div className="min-w-0">
              <p className="text-sm font-medium text-zinc-100 truncate">{currentTrack?.title}</p>
              <p
                className="text-xs text-zinc-400 truncate cursor-pointer hover:underline hover:text-zinc-200 transition"
                onClick={(e) => { e.stopPropagation(); if (currentTrack) navigateAndSearch(currentTrack.artist); }}
              >
                {currentTrack?.artist}
              </p>
            </div>
            {currentTrack && <PreserveButton track={currentTrack} size="sm" className="hidden md:flex flex-shrink-0" />}
          </div>

          {/* Controls */}
          <div className="flex-1 flex flex-col items-center gap-1">
            <div className="flex items-center gap-2 md:gap-3">
              {/* Shuffle - desktop only */}
              <button
                onClick={toggleShuffle}
                className={`hidden md:flex w-7 h-7 items-center justify-center rounded-full transition ${
                  shuffle ? 'text-emerald-400' : 'text-zinc-500 hover:text-zinc-300'
                }`}
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M16 3h5v5" />
                  <path d="M4 20 21 3" />
                  <path d="M21 16v5h-5" />
                  <path d="M15 15l6 6" />
                  <path d="M4 4l5 5" />
                </svg>
              </button>

              {/* Previous */}
              <button
                onClick={handlePrev}
                className="w-7 h-7 flex items-center justify-center text-zinc-400 hover:text-zinc-100 transition"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                  <rect x="3" y="5" width="3" height="14" />
                  <polygon points="21,5 9,12 21,19" />
                </svg>
              </button>

              {/* Play/Pause */}
              <button
                onClick={handlePlayPause}
                className="w-8 h-8 rounded-full bg-zinc-100 text-zinc-900 flex items-center justify-center hover:bg-zinc-200 transition"
              >
                {(isActiveDevice ? isPlaying : remoteIsPlaying) ? (
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                    <rect x="6" y="4" width="4" height="16" />
                    <rect x="14" y="4" width="4" height="16" />
                  </svg>
                ) : (
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                    <polygon points="5,3 19,12 5,21" />
                  </svg>
                )}
              </button>

              {/* Next */}
              <button
                onClick={handleNext}
                className="w-7 h-7 flex items-center justify-center text-zinc-400 hover:text-zinc-100 transition"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                  <polygon points="3,5 15,12 3,19" />
                  <rect x="18" y="5" width="3" height="14" />
                </svg>
              </button>

              {/* Repeat - desktop only */}
              <button
                onClick={cycleRepeat}
                className={`hidden md:flex w-7 h-7 items-center justify-center rounded-full transition relative ${
                  repeat !== 'off' ? 'text-emerald-400' : 'text-zinc-500 hover:text-zinc-300'
                }`}
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M17 2l4 4-4 4" />
                  <path d="M3 11v-1a4 4 0 014-4h14" />
                  <path d="M7 22l-4-4 4-4" />
                  <path d="M21 13v1a4 4 0 01-4 4H3" />
                </svg>
                {repeat === 'one' && (
                  <span className="absolute -top-1 -right-1 text-[9px] font-bold text-emerald-400">1</span>
                )}
              </button>
            </div>

            {/* Progress bar */}
            <div className="hidden md:flex items-center gap-2 w-full max-w-md">
              <span className="text-xs text-zinc-500 w-10 text-right">{formatTime(safeProgress)}</span>
              <div className="flex-1 h-1 bg-zinc-700 rounded-full cursor-pointer" onClick={handleSeek}>
                <div
                  className="h-full bg-zinc-300 rounded-full transition-all"
                  style={{ width: `${progressPercent}%` }}
                />
              </div>
              <span className="text-xs text-zinc-500 w-10">{formatTime(safeDuration)}</span>
            </div>
          </div>

          {/* Right side: device switcher + remote toggle */}
          <div className="flex items-center justify-end flex-shrink-0">
            <DeviceSwitcher />
          </div>
        </div>

        {/* Mobile progress bar */}
        <div className="md:hidden h-0.5 bg-zinc-800">
          <div
            className="h-full bg-zinc-400 transition-all"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>
    </>
  );
}
