// packages/web/src/pages/Admin.tsx
import { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { useAuthStore } from '@/stores/auth';
import { PasswordField } from '@/components/PasswordField';

interface UserRow {
  id: string;
  username: string;
  role: string;
  status: string;
  created_at: string;
}

export function AdminPage() {
  const currentUserId = useAuthStore((s) => {
    const token = s.token;
    if (!token) return null;
    try {
      const payload = JSON.parse(atob(token.split('.')[1]));
      return payload.sub as string;
    } catch {
      return null;
    }
  });

  const [users, setUsers] = useState<UserRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Reset password modal
  const [resetTarget, setResetTarget] = useState<UserRow | null>(null);
  const [newPassword, setNewPassword] = useState('');
  const [resetting, setResetting] = useState(false);

  // Delete confirmation
  const [deleteTarget, setDeleteTarget] = useState<UserRow | null>(null);
  const [deleting, setDeleting] = useState(false);

  // System panel
  const [systemStatus, setSystemStatus] = useState<{ slskd: { healthy: boolean; connected: boolean }; navidrome: { healthy: boolean } } | null>(null);
  const [scanStatus, setScanStatus] = useState<{ scanning: boolean; count: number } | null>(null);
  const [restarting, setRestarting] = useState<{ slskd: boolean; navidrome: boolean }>({ slskd: false, navidrome: false });
  const [logService, setLogService] = useState<'slskd' | 'navidrome'>('slskd');
  const [logs, setLogs] = useState<string[]>([]);
  const [logsLoading, setLogsLoading] = useState(false);
  const [logsLoaded, setLogsLoaded] = useState(false);

  useEffect(() => {
    loadUsers();
    loadSystemStatus();
  }, []);

  async function loadSystemStatus() {
    try {
      const [status, scan] = await Promise.all([api.getStatus(), api.getScanStatus()]);
      setSystemStatus(status);
      setScanStatus(scan);
    } catch { /* non-fatal */ }
  }

  async function handleRestart(service: 'slskd' | 'navidrome') {
    setRestarting((prev) => ({ ...prev, [service]: true }));
    try {
      await api.restartService(service);
      setTimeout(loadSystemStatus, 3000);
    } catch (err) {
      setError(err instanceof Error ? err.message : `Failed to restart ${service}`);
    } finally {
      setRestarting((prev) => ({ ...prev, [service]: false }));
    }
  }

  async function loadLogs(service: 'slskd' | 'navidrome') {
    setLogService(service);
    setLogsLoading(true);
    try {
      const res = await api.getServiceLogs(service);
      setLogs(res.logs);
    } catch {
      setLogs([`Failed to load ${service} logs`]);
    } finally {
      setLogsLoading(false);
      setLogsLoaded(true);
    }
  }

  async function loadUsers() {
    setLoading(true);
    setError(null);
    try {
      const data = await api.getUsers();
      setUsers(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load users');
    } finally {
      setLoading(false);
    }
  }

  async function toggleRole(user: UserRow) {
    const newRole = user.role === 'admin' ? 'user' : 'admin';
    try {
      await api.updateUserRole(user.id, newRole);
      setUsers((prev) => prev.map((u) => (u.id === user.id ? { ...u, role: newRole } : u)));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update role');
    }
  }

  async function toggleStatus(user: UserRow) {
    const newStatus = user.status === 'active' ? 'disabled' : 'active';
    try {
      await api.updateUserStatus(user.id, newStatus);
      setUsers((prev) => prev.map((u) => (u.id === user.id ? { ...u, status: newStatus } : u)));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update status');
    }
  }

  async function handleResetPassword() {
    if (!resetTarget || !newPassword.trim()) return;
    setResetting(true);
    try {
      await api.resetUserPassword(resetTarget.id, newPassword.trim());
      setResetTarget(null);
      setNewPassword('');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to reset password');
    } finally {
      setResetting(false);
    }
  }

  async function handleDelete() {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await api.deleteUser(deleteTarget.id);
      setUsers((prev) => prev.filter((u) => u.id !== deleteTarget.id));
      setDeleteTarget(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete user');
    } finally {
      setDeleting(false);
    }
  }

  if (loading) {
    return (
      <div className="max-w-3xl mx-auto px-3 py-4 md:px-6 md:py-8">
        <p className="text-zinc-500">Loading users...</p>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto px-3 py-4 md:px-6 md:py-8 space-y-12">
      <div>
      <h1 className="text-xl font-bold text-zinc-100 mb-8">User Management</h1>

      {error && (
        <div className="mb-6 px-4 py-2.5 rounded-lg text-sm bg-red-950/50 border border-red-900/50 text-red-400">
          {error}
          <button onClick={() => setError(null)} className="ml-2 text-red-500 hover:text-red-300">
            dismiss
          </button>
        </div>
      )}

      <section className="rounded-xl border border-zinc-800 bg-zinc-900/50 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-zinc-800">
              <th className="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">
                User
              </th>
              <th className="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">
                Role
              </th>
              <th className="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">
                Status
              </th>
              <th className="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">
                Joined
              </th>
              <th className="text-right px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            {users.map((user) => {
              const isSelf = user.id === currentUserId;
              return (
                <tr key={user.id} className="border-b border-zinc-800/50 last:border-0">
                  <td className="px-4 py-3 text-zinc-200">
                    {user.username}
                    {isSelf && <span className="ml-1.5 text-xs text-zinc-500">(you)</span>}
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className={`inline-block px-2 py-0.5 rounded text-xs font-medium ${
                        user.role === 'admin'
                          ? 'bg-amber-950/50 text-amber-400 border border-amber-900/50'
                          : 'bg-zinc-800 text-zinc-400 border border-zinc-700'
                      }`}
                    >
                      {user.role}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className={`inline-flex items-center gap-1.5 text-xs ${
                        user.status === 'active' ? 'text-emerald-400' : 'text-red-400'
                      }`}
                    >
                      <span
                        className={`w-1.5 h-1.5 rounded-full ${
                          user.status === 'active' ? 'bg-emerald-500' : 'bg-red-500'
                        }`}
                      />
                      {user.status}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-zinc-500 text-xs hidden sm:table-cell">
                    {new Date(user.created_at + 'Z').toLocaleDateString()}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <button
                        onClick={() => toggleRole(user)}
                        disabled={isSelf}
                        title={isSelf ? 'Cannot change your own role' : `Make ${user.role === 'admin' ? 'user' : 'admin'}`}
                        className="px-2 py-1 rounded text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 transition disabled:opacity-30 disabled:cursor-not-allowed"
                      >
                        {user.role === 'admin' ? 'Demote' : 'Promote'}
                      </button>
                      <button
                        onClick={() => toggleStatus(user)}
                        disabled={isSelf}
                        title={isSelf ? 'Cannot disable your own account' : `${user.status === 'active' ? 'Disable' : 'Enable'} account`}
                        className="px-2 py-1 rounded text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 transition disabled:opacity-30 disabled:cursor-not-allowed"
                      >
                        {user.status === 'active' ? 'Disable' : 'Enable'}
                      </button>
                      <button
                        onClick={() => {
                          setResetTarget(user);
                          setNewPassword('');
                        }}
                        title="Reset password"
                        className="px-2 py-1 rounded text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 transition"
                      >
                        Reset PW
                      </button>
                      <button
                        onClick={() => setDeleteTarget(user)}
                        disabled={isSelf}
                        title={isSelf ? 'Cannot delete your own account' : 'Delete user'}
                        className="px-2 py-1 rounded text-xs text-red-400/70 hover:text-red-400 hover:bg-red-950/30 transition disabled:opacity-30 disabled:cursor-not-allowed"
                      >
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </section>

      </div>

      {/* System Panel */}
      <div>
        <h2 className="text-xl font-bold text-zinc-100 mb-8">System</h2>

        {/* Service cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
          {(['slskd', 'navidrome'] as const).map((svc) => {
            const health = systemStatus?.[svc];
            const isHealthy = health?.healthy ?? false;
            const isRestarting = restarting[svc];
            return (
              <div key={svc} className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-4 flex items-center justify-between gap-4">
                <div>
                  <p className="text-sm font-medium text-zinc-200 capitalize">{svc}</p>
                  <span className={`inline-flex items-center gap-1.5 text-xs mt-1 ${isHealthy ? 'text-emerald-400' : 'text-red-400'}`}>
                    <span className={`w-1.5 h-1.5 rounded-full ${isHealthy ? 'bg-emerald-500' : 'bg-red-500'}`} />
                    {systemStatus ? (isHealthy ? 'Healthy' : 'Unreachable') : '—'}
                    {svc === 'slskd' && systemStatus && (
                      <span className="text-zinc-500 ml-1">
                        {(systemStatus.slskd as any).connected ? '· Connected' : '· Disconnected'}
                      </span>
                    )}
                  </span>
                </div>
                <button
                  onClick={() => handleRestart(svc)}
                  disabled={isRestarting}
                  className="px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-800 text-zinc-300 hover:bg-zinc-700 transition disabled:opacity-50"
                >
                  {isRestarting ? 'Restarting…' : 'Restart'}
                </button>
              </div>
            );
          })}
        </div>

        {/* Scan status */}
        {scanStatus && (
          <div className="flex items-center gap-3 mb-8 text-sm">
            <span className="text-zinc-500">Library scan:</span>
            {scanStatus.scanning ? (
              <span className="flex items-center gap-2 text-blue-400">
                <span className="inline-block w-3 h-3 border-2 border-blue-800 border-t-blue-400 rounded-full animate-spin" />
                Scanning — {scanStatus.count.toLocaleString()} songs indexed
              </span>
            ) : (
              <span className="text-zinc-400">Idle — {scanStatus.count.toLocaleString()} songs</span>
            )}
          </div>
        )}

        {/* Log viewer */}
        <div>
          <div className="flex items-center gap-3 mb-3">
            <span className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Logs</span>
            <div className="flex gap-1">
              {(['slskd', 'navidrome'] as const).map((svc) => (
                <button
                  key={svc}
                  onClick={() => loadLogs(svc)}
                  className={`px-3 py-1 rounded-md text-xs font-medium transition ${
                    logService === svc && logsLoaded
                      ? 'bg-zinc-700 text-zinc-200'
                      : 'text-zinc-500 hover:text-zinc-300'
                  }`}
                >
                  {svc}
                </button>
              ))}
            </div>
            {logsLoaded && (
              <button
                onClick={() => loadLogs(logService)}
                className="ml-auto text-xs text-zinc-500 hover:text-zinc-300 transition"
              >
                Refresh
              </button>
            )}
          </div>
          {logsLoading && (
            <div className="flex items-center gap-2 py-4 text-xs text-zinc-500">
              <span className="inline-block w-3 h-3 border-2 border-zinc-700 border-t-zinc-400 rounded-full animate-spin" />
              Loading logs…
            </div>
          )}
          {!logsLoading && logs.length > 0 && (
            <pre className="rounded-lg bg-zinc-950 border border-zinc-800 p-4 text-[11px] text-zinc-400 overflow-auto max-h-72 leading-relaxed">
              {logs.join('\n')}
            </pre>
          )}
          {!logsLoading && logsLoaded && logs.length === 0 && (
            <p className="text-xs text-zinc-600">No logs available for this service.</p>
          )}
          {!logsLoading && !logsLoaded && (
            <p className="text-xs text-zinc-600">Select a service above to view logs.</p>
          )}
        </div>
      </div>

      {/* Reset Password Modal */}
      {resetTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={() => setResetTarget(null)}>
          <div
            className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 w-full max-w-sm mx-4"
            onClick={(e) => e.stopPropagation()}
          >
            <h3 className="text-sm font-semibold text-zinc-200 mb-4">
              Reset password for {resetTarget.username}
            </h3>
            <PasswordField
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
              placeholder="New password"
              autoComplete="new-password"
              inputClassName="w-full px-4 py-2.5 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-600 focus:outline-none focus:border-zinc-500 transition text-sm"
            />
            <div className="flex justify-end gap-2 mt-4">
              <button
                onClick={() => setResetTarget(null)}
                className="px-4 py-2 rounded-lg text-sm text-zinc-400 hover:text-zinc-200 transition"
              >
                Cancel
              </button>
              <button
                onClick={handleResetPassword}
                disabled={resetting || !newPassword.trim() || newPassword.trim().length < 4}
                className="px-4 py-2 rounded-lg bg-zinc-100 text-zinc-900 text-sm font-semibold hover:bg-zinc-200 transition disabled:opacity-50"
              >
                {resetting ? 'Resetting...' : 'Reset Password'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={() => setDeleteTarget(null)}>
          <div
            className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 w-full max-w-sm mx-4"
            onClick={(e) => e.stopPropagation()}
          >
            <h3 className="text-sm font-semibold text-zinc-200 mb-2">Delete user</h3>
            <p className="text-sm text-zinc-400 mb-4">
              Are you sure you want to delete <strong className="text-zinc-200">{deleteTarget.username}</strong>?
              This action cannot be undone.
            </p>
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setDeleteTarget(null)}
                className="px-4 py-2 rounded-lg text-sm text-zinc-400 hover:text-zinc-200 transition"
              >
                Cancel
              </button>
              <button
                onClick={handleDelete}
                disabled={deleting}
                className="px-4 py-2 rounded-lg bg-red-600 text-white text-sm font-semibold hover:bg-red-500 transition disabled:opacity-50"
              >
                {deleting ? 'Deleting...' : 'Delete'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// packages/web/src/app/pages/admin/admin.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { ApiService, type AdminUser } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { PasswordFieldComponent } from '../../components/password-field/password-field.component';

@Component({
  selector: 'app-admin',
  imports: [FormsModule, PasswordFieldComponent],
  templateUrl: './admin.component.html',
  })
export class AdminComponent implements OnInit {
  private api = inject(ApiService);
  private auth = inject(AuthService);

  readonly services: ('slskd' | 'navidrome')[] = ['slskd', 'navidrome'];

  readonly users = signal<AdminUser[]>([]);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  readonly resetTarget = signal<AdminUser | null>(null);
  readonly newPassword = signal('');
  readonly resetting = signal(false);

  readonly deleteTarget = signal<AdminUser | null>(null);
  readonly deleting = signal(false);

  readonly systemStatus = signal<{ slskd: { healthy: boolean; connected?: boolean }; navidrome: { healthy: boolean } } | null>(null);
  readonly scanStatus = signal<{ scanning: boolean; count: number } | null>(null);
  readonly restarting = signal<{ slskd: boolean; navidrome: boolean }>({ slskd: false, navidrome: false });
  readonly logService = signal<'slskd' | 'navidrome'>('slskd');
  readonly logs = signal<string[]>([]);
  readonly logHint = signal<string | null>(null);
  readonly logsLoading = signal(false);
  readonly logsLoaded = signal(false);

  currentUserId(): string | null {
    const token = this.auth.token();
    if (!token) return null;
    try {
      const payload = JSON.parse(atob(token.split('.')[1]));
      return payload.sub as string;
    } catch { return null; }
  }

  ngOnInit(): void {
    this.loadUsers();
    this.loadSystemStatus();
  }

  formatDate(dateStr: string): string {
    return new Date(dateStr + 'Z').toLocaleDateString();
  }

  getBadgeColor(svc: 'slskd' | 'navidrome'): string {
    const status = this.systemStatus();
    if (!status) return 'text-zinc-500';
    const health = status[svc];
    if (svc === 'slskd') {
      const connected = (health as any)?.connected;
      return connected ? 'text-emerald-400' : health.healthy ? 'text-amber-400' : 'text-red-400';
    }
    return health.healthy ? 'text-emerald-400' : 'text-red-400';
  }

  getDotColor(svc: 'slskd' | 'navidrome'): string {
    const status = this.systemStatus();
    if (!status) return 'bg-zinc-500';
    const health = status[svc];
    if (svc === 'slskd') {
      const connected = (health as any)?.connected;
      return connected ? 'bg-emerald-500' : health.healthy ? 'bg-amber-400' : 'bg-red-500';
    }
    return health.healthy ? 'bg-emerald-500' : 'bg-red-500';
  }

  getBadgeLabel(svc: 'slskd' | 'navidrome'): string {
    const status = this.systemStatus();
    if (!status) return '—';
    const health = status[svc];
    if (svc === 'slskd') {
      const connected = (health as any)?.connected;
      return connected ? 'Connected' : health.healthy ? 'Disconnected' : 'Unreachable';
    }
    return health.healthy ? 'Healthy' : 'Unreachable';
  }

  async toggleRole(user: AdminUser): Promise<void> {
    const newRole = user.role === 'admin' ? 'user' : 'admin';
    try {
      await firstValueFrom(this.api.updateUserRole(user.id, newRole as 'admin' | 'user'));
      this.users.update(prev => prev.map(u => u.id === user.id ? { ...u, role: newRole } : u));
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Failed to update role');
    }
  }

  async toggleStatus(user: AdminUser): Promise<void> {
    const newStatus = user.status === 'active' ? 'disabled' : 'active';
    try {
      await firstValueFrom(this.api.updateUserStatus(user.id, newStatus as 'active' | 'disabled'));
      this.users.update(prev => prev.map(u => u.id === user.id ? { ...u, status: newStatus } : u));
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Failed to update status');
    }
  }

  async handleResetPassword(): Promise<void> {
    const target = this.resetTarget();
    if (!target || !this.newPassword().trim()) return;
    this.resetting.set(true);
    try {
      await firstValueFrom(this.api.resetUserPassword(target.id, this.newPassword().trim()));
      this.resetTarget.set(null);
      this.newPassword.set('');
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Failed to reset password');
    } finally {
      this.resetting.set(false);
    }
  }

  async handleDeleteUser(): Promise<void> {
    const target = this.deleteTarget();
    if (!target) return;
    this.deleting.set(true);
    try {
      await firstValueFrom(this.api.deleteUser(target.id));
      this.users.update(prev => prev.filter(u => u.id !== target.id));
      this.deleteTarget.set(null);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Failed to delete user');
    } finally {
      this.deleting.set(false);
    }
  }

  async handleRestart(service: 'slskd' | 'navidrome'): Promise<void> {
    this.restarting.update(prev => ({ ...prev, [service]: true }));
    try {
      await firstValueFrom(this.api.restartService(service));
      setTimeout(() => this.loadSystemStatus(), 3000);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : `Failed to restart ${service}`);
    } finally {
      this.restarting.update(prev => ({ ...prev, [service]: false }));
    }
  }

  async loadLogs(service: 'slskd' | 'navidrome'): Promise<void> {
    this.logService.set(service);
    this.logsLoading.set(true);
    this.logHint.set(null);
    try {
      const res = await firstValueFrom(this.api.getServiceLogs(service));
      this.logs.set(res.logs);
      this.logHint.set(res.hint ?? null);
    } catch {
      this.logs.set([`Failed to load ${service} logs`]);
    } finally {
      this.logsLoading.set(false);
      this.logsLoaded.set(true);
    }
  }

  private async loadUsers(): Promise<void> {
    this.loading.set(true);
    this.error.set(null);
    try {
      const data = await firstValueFrom(this.api.getUsers());
      this.users.set(data);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Failed to load users');
    } finally {
      this.loading.set(false);
    }
  }

  private async loadSystemStatus(): Promise<void> {
    try {
      const [status, scan] = await Promise.all([
        firstValueFrom(this.api.getStatus()),
        firstValueFrom(this.api.getScanStatus()),
      ]);
      this.systemStatus.set(status as any);
      this.scanStatus.set(scan);
    } catch { /* non-fatal */ }
  }
}


    @if (loading()) {
      <div class="max-w-3xl mx-auto px-3 py-4 md:px-6 md:py-8">
        <p class="text-zinc-500">Loading users...</p>
      </div>
    } @else {
      <div class="max-w-3xl mx-auto px-3 py-4 md:px-6 md:py-8 space-y-12">
        <!-- User Management -->
        <div>
          <div class="flex items-center justify-between mb-8">
            <h1 class="text-xl font-bold text-theme-primary">User Management</h1>
            <button (click)="showCreateUser.set(true)"
              class="px-3 py-1.5 rounded-lg text-xs font-medium bg-theme-inverse text-theme-inverse hover:opacity-90 transition">
              Create User
            </button>
          </div>

          @if (error()) {
            <div class="mb-6 px-4 py-2.5 rounded-lg text-sm bg-red-950/50 border border-red-900/50 text-red-400">
              {{ error() }}
              <button (click)="error.set(null)" class="ml-2 text-red-500 hover:text-red-300">dismiss</button>
            </div>
          }

          <section class="rounded-xl border border-zinc-800 bg-zinc-900/50 overflow-x-auto">
            <table class="w-full text-sm">
              <thead>
                <tr class="border-b border-zinc-800">
                  <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">User</th>
                  <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">Role</th>
                  <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">Status</th>
                  <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Online</th>
                  <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Devices</th>
                  <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Sessions</th>
                  <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Joined</th>
                  <th class="text-right px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">Actions</th>
                </tr>
              </thead>
              <tbody>
                @for (user of users(); track user.id) {
                  <tr class="border-b border-zinc-800/50 last:border-0">
                    <td class="px-4 py-3 text-zinc-200">
                      {{ user.username }}
                      @if (user.id === currentUserId()) { <span class="ml-1.5 text-xs text-zinc-500">(you)</span> }
                    </td>
                    <td class="px-4 py-3">
                      <span [class]="'inline-block px-2 py-0.5 rounded text-xs font-medium ' + (user.role === 'admin' ? 'bg-amber-950/50 text-amber-400 border border-amber-900/50' : 'bg-zinc-800 text-zinc-400 border border-zinc-700')">
                        {{ user.role }}
                      </span>
                    </td>
                    <td class="px-4 py-3">
                      <span [class]="'inline-flex items-center gap-1.5 text-xs ' + (user.status === 'active' ? 'text-emerald-400' : 'text-red-400')">
                        <span [class]="'w-1.5 h-1.5 rounded-full ' + (user.status === 'active' ? 'bg-emerald-500' : 'bg-red-500')"></span>
                        {{ user.status }}
                      </span>
                    </td>
                    <td class="px-4 py-3 hidden sm:table-cell">
                      <span [class]="'inline-block w-1.5 h-1.5 rounded-full ' + (user.isConnected ? 'bg-emerald-500' : 'bg-zinc-600')"
                        [title]="user.isConnected ? 'Online' : 'Offline'"></span>
                    </td>
                    <td class="px-4 py-3 text-zinc-400 text-xs hidden sm:table-cell">
                      {{ user.amountOfDevices }}
                    </td>
                    <td class="px-4 py-3 text-zinc-400 text-xs hidden sm:table-cell">
                      {{ user.amountOfSessions }}
                    </td>
                    <td class="px-4 py-3 text-zinc-500 text-xs hidden sm:table-cell">
                      {{ formatDate(user.created_at) }}
                    </td>
                    <td class="px-4 py-3 text-right">
                      <div class="flex items-center justify-end gap-1">
                        <button (click)="toggleRole(user)" [disabled]="user.id === currentUserId()"
                          [title]="user.id === currentUserId() ? 'Cannot change your own role' : 'Make ' + (user.role === 'admin' ? 'user' : 'admin')"
                          class="px-2 py-1 rounded text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 transition disabled:opacity-30 disabled:cursor-not-allowed">
                          {{ user.role === 'admin' ? 'Demote' : 'Promote' }}
                        </button>
                        <button (click)="toggleStatus(user)" [disabled]="user.id === currentUserId()"
                          class="px-2 py-1 rounded text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 transition disabled:opacity-30 disabled:cursor-not-allowed">
                          {{ user.status === 'active' ? 'Disable' : 'Enable' }}
                        </button>
                        <button (click)="resetTarget.set(user); newPassword.set('')"
                          class="px-2 py-1 rounded text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 transition">
                          Reset PW
                        </button>
                        <button (click)="deleteTarget.set(user)" [disabled]="user.id === currentUserId()"
                          class="px-2 py-1 rounded text-xs text-red-400/70 hover:text-red-400 hover:bg-red-950/30 transition disabled:opacity-30 disabled:cursor-not-allowed">
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </section>
        </div>

        <!-- System Panel -->
        <div>
          <h2 class="text-xl font-bold text-theme-primary mb-8">System</h2>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
            @for (svc of services; track svc) {
              <div class="rounded-xl border border-zinc-800 bg-zinc-900/50 p-4 flex items-center justify-between gap-4">
                <div>
                  <p class="text-sm font-medium text-zinc-200 capitalize">{{ svc }}</p>
                  <span [class]="'inline-flex items-center gap-1.5 text-xs mt-1 ' + getBadgeColor(svc)">
                    <span [class]="'w-1.5 h-1.5 rounded-full ' + getDotColor(svc)"></span>
                    {{ getBadgeLabel(svc) }}
                  </span>
                </div>
                <button (click)="handleRestart(svc)" [disabled]="restarting()[svc]"
                  class="px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-800 text-zinc-300 hover:bg-zinc-700 transition disabled:opacity-50">
                  {{ restarting()[svc] ? 'Restarting…' : 'Restart' }}
                </button>
              </div>
            }
          </div>

          @if (scanStatus()) {
            <div class="flex items-center gap-3 mb-8 text-sm">
              <span class="text-zinc-500">Library scan:</span>
              @if (scanStatus()!.scanning) {
                <span class="flex items-center gap-2 text-blue-400">
                  <span class="inline-block w-3 h-3 border-2 border-blue-800 border-t-blue-400 rounded-full animate-spin"></span>
                  Scanning — {{ scanStatus()!.count.toLocaleString() }} songs indexed
                </span>
              } @else {
                <span class="text-zinc-400">Idle — {{ scanStatus()!.count.toLocaleString() }} songs</span>
              }
            </div>
          }

          <!-- Maintenance: library-wide metadata optimization -->
          <div class="flex flex-col gap-2 mb-8">
            <div class="flex items-center gap-3">
              <button (click)="optimizeAllMetadata()" [disabled]="optimizingMetadata()"
                data-testid="optimize-all-metadata"
                class="px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-800 text-zinc-300 hover:bg-zinc-700 transition disabled:opacity-50">
                {{ optimizingMetadata() ? 'Optimizing…' : 'Optimize metadata' }}
              </button>
              <span class="text-xs text-zinc-500">Re-fetch missing/poor covers &amp; years from Lidarr.</span>
            </div>
            @if (optimizeMetadataMsg(); as msg) {
              <p class="text-xs text-zinc-400" data-testid="optimize-all-msg">{{ msg }}</p>
            }
          </div>

          <!-- Log viewer -->
          <div>
            <span class="text-xs font-semibold uppercase tracking-wider text-zinc-500">Logs</span>

            <!-- Service selector -->
            <div class="flex gap-2 mb-3 flex-wrap mt-3">
              @for (svc of logServiceOptions; track svc) {
                <button
                  (click)="selectLogService(svc)"
                  [class]="selectedService() === svc
                    ? 'px-3 py-1 rounded text-sm font-medium bg-theme-accent text-white'
                    : 'px-3 py-1 rounded text-sm font-medium bg-theme-surface text-theme-muted hover:text-theme-text'"
                >{{ svc }}</button>
              }
            </div>

            <!-- Status indicator -->
            <div class="text-xs mb-2">
              @if (logStreamStatus() === 'connecting') {
                <span class="text-amber-400">Reconnecting…</span>
              } @else if (logStreamStatus() === 'connected') {
                <span class="text-emerald-400">Live</span>
              } @else if (logStreamStatus() === 'disconnected') {
                <span class="text-red-400">Disconnected — <button class="underline" (click)="connectLogStream()">reconnect</button></span>
              }
            </div>

            <!-- Log output -->
            <div class="log-scroll-container bg-theme-surface rounded p-3 h-80 overflow-y-auto font-mono text-xs text-theme-muted">
              @if (logLines().length === 0) {
                <div class="text-theme-muted/50">Waiting for log output…</div>
              }
              @for (line of logLines(); track $index) {
                <div class="whitespace-pre-wrap break-all leading-relaxed">{{ line }}</div>
              }
            </div>
          </div>
        </div>

        <!-- Incomplete Albums (3A) -->
        <div>
          <div class="flex items-center justify-between mb-8">
            <h2 class="text-xl font-bold text-theme-primary">Incomplete Albums</h2>
            <button (click)="loadIncompleteJobs()"
              class="px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-800 text-zinc-300 hover:bg-zinc-700 transition">
              Refresh
            </button>
          </div>

          @if (jobsLoading()) {
            <p class="text-zinc-500 text-sm">Loading album jobs…</p>
          } @else if (incompleteJobs().length === 0) {
            <p class="text-zinc-500 text-sm">No incomplete album hunts. 🎉</p>
          } @else {
            <section class="rounded-xl border border-zinc-800 bg-zinc-900/50 overflow-x-auto">
              <table class="w-full text-sm">
                <thead>
                  <tr class="border-b border-zinc-800">
                    <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">Album</th>
                    <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">State</th>
                    <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Attempts</th>
                    <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Created</th>
                    <th class="text-right px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  @for (job of incompleteJobs(); track job.id) {
                    <tr class="border-b border-zinc-800/50 last:border-0">
                      <td class="px-4 py-3 text-zinc-200">
                        <div class="font-medium">{{ job.albumTitle ?? job.directory }}</div>
                        @if (job.artistName) { <div class="text-xs text-zinc-500">{{ job.artistName }}</div> }
                      </td>
                      <td class="px-4 py-3">
                        <span [class]="'text-xs font-medium ' + jobStateClass(job.state)">{{ job.state }}</span>
                      </td>
                      <td class="px-4 py-3 text-zinc-500 text-xs hidden sm:table-cell">{{ job.fallbackAttempts }}</td>
                      <td class="px-4 py-3 text-zinc-500 text-xs hidden sm:table-cell">{{ formatTimestamp(job.createdAt) }}</td>
                      <td class="px-4 py-3 text-right">
                        <button (click)="retryHunt(job)" [disabled]="job.lidarrAlbumId == null"
                          [title]="job.lidarrAlbumId == null ? 'No Lidarr album id recorded' : 'Re-hunt this album'"
                          class="px-3 py-1.5 rounded-lg text-xs font-medium bg-theme-inverse text-theme-inverse hover:opacity-90 transition disabled:opacity-40 disabled:cursor-not-allowed">
                          Retry hunt
                        </button>
                      </td>
                    </tr>
                  }
                </tbody>
              </table>
            </section>
          }
        </div>

        <!-- Untracked Downloads (3E) -->
        <div>
          <div class="flex items-center justify-between mb-8">
            <h2 class="text-xl font-bold text-theme-primary">
              Untracked Downloads
              @if (untrackedTotal() > 0) { <span class="ml-2 text-sm font-normal text-zinc-500">{{ untrackedTotal() }} total</span> }
            </h2>
            <button (click)="loadUntracked()"
              class="px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-800 text-zinc-300 hover:bg-zinc-700 transition">
              Refresh
            </button>
          </div>

          <p class="text-xs text-zinc-500 mb-4">
            Completed downloads with no recorded library path (predate the organizer). Run
            <code class="px-1 py-0.5 rounded bg-zinc-800 text-zinc-300">bun run packages/api/src/scripts/backfill-untracked.ts --apply</code>
            to resolve the ones still on disk.
          </p>

          @if (untrackedLoading()) {
            <p class="text-zinc-500 text-sm">Loading…</p>
          } @else if (untracked().length === 0) {
            <p class="text-zinc-500 text-sm">No untracked downloads. 🎉</p>
          } @else {
            <section class="rounded-xl border border-zinc-800 bg-zinc-900/50 overflow-x-auto">
              <table class="w-full text-sm">
                <thead>
                  <tr class="border-b border-zinc-800">
                    <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">File</th>
                    <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Peer folder</th>
                    <th class="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 hidden sm:table-cell">Completed</th>
                  </tr>
                </thead>
                <tbody>
                  @for (row of untracked(); track row.transferKey) {
                    <tr class="border-b border-zinc-800/50 last:border-0">
                      <td class="px-4 py-3 text-zinc-300 break-all">{{ row.filename }}</td>
                      <td class="px-4 py-3 text-zinc-500 text-xs hidden sm:table-cell break-all">{{ row.directory }}</td>
                      <td class="px-4 py-3 text-zinc-500 text-xs hidden sm:table-cell">{{ formatTimestamp(row.completedAt) }}</td>
                    </tr>
                  }
                </tbody>
              </table>
            </section>
          }
        </div>

        <!-- Retry-hunt modal (reuses the album-hunt flow) -->
        @if (retryAlbum(); as album) {
          <app-album-hunt-modal
            [album]="album"
            [artistName]="retryArtist()"
            [replace]="true"
            (closed)="onRetryClosed()"
            (downloaded)="onRetryDownloaded()" />
        }

        <!-- Create User Modal -->
        @if (showCreateUser()) {
          <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60" (click)="showCreateUser.set(false)">
            <div class="bg-zinc-900 border border-zinc-800 rounded-xl p-6 w-full max-w-sm mx-4" (click)="$event.stopPropagation()">
              <h3 class="text-sm font-semibold text-zinc-200 mb-4">Create new user</h3>
              <div class="space-y-3">
                <input type="text" [ngModel]="newUsername()" (ngModelChange)="newUsername.set($event)"
                  placeholder="Username" autocomplete="off"
                  class="w-full px-4 py-2.5 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-600 focus:outline-none focus:border-zinc-500 transition text-sm" />
                <app-password-field [ngModel]="newUserPassword()" (ngModelChange)="newUserPassword.set($event)"
                  placeholder="Password" autocomplete="new-password"
                  inputClass="w-full px-4 py-2.5 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-600 focus:outline-none focus:border-zinc-500 transition text-sm" />
              </div>
              <div class="flex justify-end gap-2 mt-4">
                <button (click)="showCreateUser.set(false)" class="px-4 py-2 rounded-lg text-sm text-zinc-400 hover:text-zinc-200 transition">Cancel</button>
                <button (click)="handleCreateUser()" [disabled]="creating() || !newUsername().trim() || newUserPassword().trim().length < 4"
                  class="px-4 py-2 rounded-lg bg-theme-inverse text-theme-inverse text-sm font-semibold hover:opacity-90 transition disabled:opacity-50">
                  {{ creating() ? 'Creating...' : 'Create User' }}
                </button>
              </div>
            </div>
          </div>
        }

        <!-- Reset Password Modal -->
        @if (resetTarget()) {
          <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60" (click)="resetTarget.set(null)">
            <div class="bg-zinc-900 border border-zinc-800 rounded-xl p-6 w-full max-w-sm mx-4" (click)="$event.stopPropagation()">
              <h3 class="text-sm font-semibold text-zinc-200 mb-4">Reset password for {{ resetTarget()!.username }}</h3>
              <app-password-field [ngModel]="newPassword()" (ngModelChange)="newPassword.set($event)"
                placeholder="New password" autocomplete="new-password"
                inputClass="w-full px-4 py-2.5 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-100 placeholder-zinc-600 focus:outline-none focus:border-zinc-500 transition text-sm" />
              <div class="flex justify-end gap-2 mt-4">
                <button (click)="resetTarget.set(null)" class="px-4 py-2 rounded-lg text-sm text-zinc-400 hover:text-zinc-200 transition">Cancel</button>
                <button (click)="handleResetPassword()" [disabled]="resetting() || !newPassword().trim() || newPassword().trim().length < 4"
                  class="px-4 py-2 rounded-lg bg-theme-inverse text-theme-inverse text-sm font-semibold hover:opacity-90 transition disabled:opacity-50">
                  {{ resetting() ? 'Resetting...' : 'Reset Password' }}
                </button>
              </div>
            </div>
          </div>
        }

        <!-- Delete Confirmation Modal -->
        @if (deleteTarget()) {
          <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60" (click)="deleteTarget.set(null)">
            <div class="bg-zinc-900 border border-zinc-800 rounded-xl p-6 w-full max-w-sm mx-4" (click)="$event.stopPropagation()">
              <h3 class="text-sm font-semibold text-zinc-200 mb-2">Delete user</h3>
              <p class="text-sm text-zinc-400 mb-4">
                Are you sure you want to delete <strong class="text-zinc-200">{{ deleteTarget()!.username }}</strong>? This action cannot be undone.
              </p>
              <div class="flex justify-end gap-2">
                <button (click)="deleteTarget.set(null)" class="px-4 py-2 rounded-lg text-sm text-zinc-400 hover:text-zinc-200 transition">Cancel</button>
                <button (click)="handleDeleteUser()" [disabled]="deleting()"
                  class="px-4 py-2 rounded-lg bg-red-600 text-white text-sm font-semibold hover:bg-red-500 transition disabled:opacity-50">
                  {{ deleting() ? 'Deleting...' : 'Delete' }}
                </button>
              </div>
            </div>
          </div>
        }
      </div>
    }
